/**
 * 뉴스 데이터 — 뉴스룸 목록(/news)과 상세(/news/[id]) 페이지의 단일 소스.
 *
 * gemiso.co.kr/news 의 언론보도(보도자료) 클리핑 139건을 추출해 정적 데이터로
 * 구성한 것. 최신순으로 정렬돼 있으며, 첫 항목이 주요 소식(featured)이 된다.
 * 새 소식은 이 배열 맨 앞에 항목을 추가하면 목록·상세가 자동으로 갱신된다.
 *
 * 이미지는 public/assets/news 에 저장돼 있고, image 값은 basePath 없이
 * 기록한다(컴포넌트에서 asset()으로 경로를 보정).
 */

export type NewsArticle = {
  /** URL 식별자(숫자) */
  id: number;
  /** 보도 매체명 — 없으면 빈 문자열 */
  outlet: string;
  /** 발행일 (YYYY.MM.DD) */
  date: string;
  /** 기사 제목 */
  title: string;
  /** 요약 본문 */
  summary: string;
  /** 원문 기사 URL — 없으면 빈 문자열 */
  href: string;
  /** 대표 이미지 경로(/assets/news/...) — 없으면 null */
  image: string | null;
};

/** 최신순으로 정렬된 보도 클리핑 목록. */
export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 140,
    outlet: "뉴시스",
    date: "2026.04.30",
    title: "제머나이소프트, 정부 방송미디어 R&D '마이미디어 플랫폼 핵심기술개발' 총괄",
    summary:
      "제머나이소프트가 방송미디어통신위원회·정보통신기획평가원(IITP)이 선정한 디지털미디어 혁신기술 개발 과제 중 '개인 맞춤형 미디어 서비스 구현을 위한 마이미디어 플랫폼 핵심기술개발'을 총괄한다. KETI·ETRI와 함께 페르소나 AI 모델과 메타데이터 기술을 결합해 이용자의 시청 흐름과 관심사를 반영, 콘텐츠를 재구성하고 장면을 자동 연결하는 개인화 기술을 개발한다. 정부는 2030년까지 5년간 727억여원을 방송미디어 R&D에 투입한다.",
    href: "https://www.newsis.com/view/NISX20260430_0003613403",
    image: "/assets/news/news-0140.jpg",
  },
  {
    id: 141,
    outlet: "",
    date: "2026.04.18",
    title: "제머나이소프트, 'NAB Show 2026' 참가 — 방송 콘텐츠 기반 AI 학습 데이터 선봬",
    summary:
      "제머나이소프트가 미국 라스베이거스에서 열리는 세계 최대 방송·미디어 전시회 'NAB Show 2026'(Central Hall, Futures Park C4449-G)에 참가한다. 'Better Data. Better AI.'를 슬로건으로, 방송 영상 콘텐츠에서 고품질 AI 학습 데이터셋을 구축하는 엔드-투-엔드 서비스를 선보인다. 데이터 전략 컨설팅부터 3단계 CoT 라벨링·품질보증, text-to-image·text-to-video 샘플 모델 개발까지 전 과정을 아우른다.",
    href: "https://www.gemiso.com/ai-dataset",
    image: null,
  },
  {
    id: 139,
    outlet: "IT조선",
    date: "2026.01.30",
    title: "제머나이소프트, KBS 멀티플랫폼 통합주조 구축 사업 참여",
    summary: "제머나이소프트가 KBS 멀티플랫폼 통합주조 구축 사업에 참여해 콘텐츠 통합관리(MAM) 및 AI 기반 영상 품질 관리 솔루션을 공급한다.",
    href: "https://it.chosun.com/news/articleView.html?idxno=2023092156052",
    image: "/assets/news/news-0139.png",
  },
  {
    id: 138,
    outlet: "디지털타임즈",
    date: "2026.01.30",
    title: "제머나이소프트, KBS 멀티플랫폼 통합주조 구축 사업 공급 파트너 선정",
    summary: "제머나이소프트가 KBS ‘멀티플랫폼 통합주조 구축 사업’에서 콘텐츠 통합관리(MAM) 시스템 및 AI 기반 QC 솔루션의 공급 파트너로 선정됐다.",
    href: "https://www.dt.co.kr/article/12043867?ref=naver",
    image: "/assets/news/news-0138.png",
  },
  {
    id: 137,
    outlet: "전자신문",
    date: "2026.01.30",
    title: "제머나이소프트, KBS 멀티플랫폼 통합주조 구축 사업 공급 파트너 선정",
    summary: "제머나이소프트가 KBS 멀티플랫폼 통합주조 구축 사업에서 콘텐츠 통합관리(MAM) 및 AI 기반 영상 품질 관리(QC) 솔루션 공급 파트너로 선정됐다.",
    href: "https://www.etnews.com/20260130000251",
    image: "/assets/news/news-0137.png",
  },
  {
    id: 136,
    outlet: "매일신문",
    date: "2026.01.13",
    title: "제머나이소프트, 유료방송사업자 지역채널에 자동송출 솔루션 '탈로스' 공급",
    summary: "제머나이소프트, 유료방송사업자 지역채널에 자동송출 솔루션 '탈로스' 공급",
    href: "https://www.imaeil.com/page/view/2026011413551706783",
    image: "/assets/news/news-0136.png",
  },
  {
    id: 135,
    outlet: "전자신문",
    date: "2026.01.13",
    title: "제머나이소프트, 대형 유료방송사업자 지역채널 DR 시스템에 자동송출 솔루션 '탈로스' 공급",
    summary: "제머나이소프트, 대형 유료방송사업자 지역채널 DR 시스템에 자동송출 솔루션 '탈로스' 공급",
    href: "https://www.etnews.com/20260113000338",
    image: "/assets/news/news-0135.png",
  },
  {
    id: 134,
    outlet: "디지털데일리",
    date: "2026.01.13",
    title: "제머나이소프트, 유료방송 지역채널 DR 송출시스템 공급",
    summary: "제머나이소프트, 유료방송 지역채널 DR 송출시스템 공급",
    href: "https://www.ddaily.co.kr/page/view/2026011314485519847",
    image: "/assets/news/news-0134.png",
  },
  {
    id: 133,
    outlet: "",
    date: "2025.03.17",
    title: "포바이포, 제머나이소프트와 AI 솔루션 플러그인 공동 개발 MOU 체결",
    summary: "포바이포의 화질 개선 AI ‘픽셀(PIXELL)’, 제머나이소프트의 미디어 자산 관리 시스템에 최적화된 플러그인 형태로 제공",
    href: "https://search.naver.com/search.naver?sm=tab_hty.top&amp;where=news&amp;ssc=tab.news.all&amp;query=%EC%A0%9C%EB%A8%B8%EB%82%98%EC%9D%B4%EC%86%8C%ED%94%84%ED%8A%B8+AI+%EC%86%94%EB%A3%A8%EC%85%98+%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8&amp;oquery=%EC%A0%9C%EB%A8%B8%EB%82%98%EC%9D%B4%EC%86%8C%ED%94%84%ED%8A%B8+ai+%EC%86%94%EB%A3%A8%EC%85%98+%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8&amp;tqi=i9X9PspzL8VssESLEvNssssssXw-511880&amp;nso=so%3Ar%2Cp%3Aall%2Ca%3Aall&amp;mynews=0&amp;office_section_code=0&amp;office_type=0&amp;pd=0&amp;photo=0&amp;sort=0",
    image: "/assets/news/news-0133.png",
  },
  {
    id: 132,
    outlet: "",
    date: "2025.02.25",
    title: "제머나이소프트, 2025 NAB Show 참가",
    summary: "제머나이소프트가 NAB Show 2025에서 최신 미디어 워크플로 기술을 선보입니다.\n콘텐츠 관리를 혁신하는 솔루션을 직접 경험해 보세요!",
    href: "https://nab25.mapyourshow.com/8_0/exhibitor/exhibitor-details.cfm?exhid=8800723",
    image: "/assets/news/news-0132.png",
  },
  {
    id: 131,
    outlet: "",
    date: "2025.02.20",
    title: "제머나이소프트, '제38회 한국영상기자상 시상식' 공식 후원",
    summary: "디지털 미디어 관리 기업 제머나이소프트가 국내 보도영상 분야 최고의 권위를 자랑하는 '제38회 한국영상기자상 시상식'에 공식 후원사로 참여했다.",
    href: "https://7bafc12f-77bb-4c18-aa3b-3df2789078ed.usrfiles.com/ugd/7bafc1_f10a7c7dd80249218e1e327e64261891.pdf",
    image: "/assets/news/news-0131.jpg",
  },
  {
    id: 130,
    outlet: "",
    date: "2024.10.28",
    title: "제머나이소프트, 'Video Dev Days 2024' 공식 후원 발표",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트가 오픈소스 비디오 라이브러리 및 비디오 플레이어 개발 조직인 VideoLAN이 주최하는 'Video Dev Days 2024'에 공식 후원사로 참여한다고 밝혔다.",
    href: "https://www.etnews.com/20241025000295",
    image: "/assets/news/news-0130.png",
  },
  {
    id: 129,
    outlet: "",
    date: "2024.10.28",
    title: "제머나이소프트, 'Video Dev Days 2024' 공식 후원사로 참여",
    summary: "디지털 미디어 관리 기업 제머나이소프트가 11월 2일 광운대학교에서 열리는 VideoLAN 주최의 'Video Dev Days 2024'에 공식 후원사로 나선다.",
    href: "https://www.wowtv.co.kr/NewsCenter/News/Read?articleId=A202410250349&amp;t=NN",
    image: "/assets/news/news-0129.png",
  },
  {
    id: 128,
    outlet: "",
    date: "2024.10.25",
    title: "제머나이소프트, 'Video Dev Days 2024' 공식 후원 오픈소스 멀티미디어 생태계 발전에 기여",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트(대표 강진욱)가 VideoLAN이 주최하는 'Video Dev Days 2024'에 공식 후원사로 참여한다고 밝혔다",
    href: "https://www.videosound.co.kr/situation_news/?q=YToxOntzOjEyOiJrZXl3b3JkX3R5cGUiO3M6MzoiYWxsIjt9&amp;bmode=view&amp;idx=123431066&amp;t=board",
    image: "/assets/news/news-0128.png",
  },
  {
    id: 127,
    outlet: "",
    date: "2024.04.04",
    title: "한국외대, ‘백남준의 비디오 서재’ 비디오아트 아카이브 세미나 개최",
    summary: "한국외국어대학교 정보·기록학연구소가 7일, ‘백남준의 비디오 서재’를 주제로, 한국 비디오 아티스트 백남준의 비디오 아카이브와 관련한 온라인 화상 세미나를 개최했다.",
    href: "https://m.dhnews.co.kr/news/view/1065579738924891",
    image: "/assets/news/news-0127.png",
  },
  {
    id: 126,
    outlet: "",
    date: "2023.12.08",
    title: "제머나이소프트, 에이디소프트와 제품 및 기술 이전 계약 체결",
    summary: "자사 비디오 기술과 에이디소프트 라디오 솔루션 기술 통합",
    href: "http://www.itdaily.kr/news/articleView.html?idxno=218716",
    image: "/assets/news/news-0126.png",
  },
  {
    id: 125,
    outlet: "",
    date: "2023.12.08",
    title: "제머나이소프트, 에이디소프트와 제품 및 기술 이전·통합 계약 체결",
    summary: "제머나이소프트가 에이디소프트와 지난 4일 제품 및 기술 이전·통합 계약을 체결했다.",
    href: "https://www.etnews.com/20231208000152",
    image: "/assets/news/news-0125.png",
  },
  {
    id: 124,
    outlet: "",
    date: "2023.12.08",
    title: "제머나이소프트-에이디소프트, 라디오·오디오 솔루션 제품 및 기술 이전 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문기업 (주)제머나이소프트와 라디오 방송 시스템 전문기업 (주)에이디소프트가 지난 4일 제품 및 기술 이전·통합 계약을 체결했다고 전했다.",
    href: "https://www.segye.com/newsView/20231208511608?OutUrl=naver",
    image: "/assets/news/news-0124.png",
  },
  {
    id: 123,
    outlet: "",
    date: "2023.11.24",
    title: "아리랑TV, 이중언어 AI 앵커 고도화…글로벌 혁신 주도",
    summary: "올해 아리랑TV는 AI 분야 전문 기업인 딥브레인 AI, 자이냅스, 제머나이소프트와의 협력을 통해 성공적으로 이중언어 AI 앵커 프로젝트를 완성했다. 그 결과 AI 휴먼 및 이중언어 처리 기술의 높은 수준을 구현하였으며, 아리랑TV는 이를 활용한 뉴스 프로그램 정규 방송으로 미디어 혁신의 새로운 표준을 제시할 것으로 기대된다.",
    href: "https://n.news.naver.com/mnews/article/015/0004917945?sid=105",
    image: "/assets/news/news-0123.jpg",
  },
  {
    id: 122,
    outlet: "",
    date: "2023.11.24",
    title: "아리랑TV, 국내 최초로 AI 앵커 생방송 뉴스 선보여",
    summary: "올해 아리랑TV는 AI 분야 전문 기업인 딥브레인 AI, 자이냅스, 제머나이소프트와의 협력을 통해 이중언어 AI 앵커 프로젝트를 완성했다. 아리랑TV 측은 “AI 휴먼 및 이중언어 처리 기술을 높은 수준으로 구현했다”면서 “이를 활용한 뉴스 프로그램을 통해 미디어 혁신의 새 표준을 제시할 것”이라고 자신했다.",
    href: "https://www.kukinews.com/newsView/kuk202311240081",
    image: "/assets/news/news-0122.jpg",
  },
  {
    id: 121,
    outlet: "",
    date: "2023.11.23",
    title: "아리랑TV, 2개 국어 AI 앵커가 진행하는 뉴스 프로그램 신설",
    summary: "아리랑TV는 AI 앵커가 진행하는 뉴스 프로그램을 신설한다고 23일 밝혔다.",
    href: "https://www.yna.co.kr/view/AKR20231123139000005?input=1195m",
    image: "/assets/news/news-0121.jpg",
  },
  {
    id: 120,
    outlet: "정보통신신문",
    date: "2021.12.16",
    title: "제머나이소프트 컨소시엄, 혼합현실 서비스 시연",
    summary: "‘KMF & KME 2021’ 출품\n융합서비스 경쟁력 강화 과제 성과\n고가장비 없이 손쉽게 AR영상 제작",
    href: "https://www.koit.co.kr/news/articleView.html?idxno=91950",
    image: "/assets/news/news-0120.jpg",
  },
  {
    id: 119,
    outlet: "뉴스와이어",
    date: "2021.12.15",
    title: "제머나이소프트 컨소시엄, ICT 융합 서비스 경쟁력 강화 과제 성과 전시",
    summary: "제머나이소프트, 광운대학교 공간컴퓨팅연구실, 한국가상증강현실산업협회, 공간의파티(이하 컨소시엄)는 ‘유니버설 혼합 현실 서비스를 위한 AR Cloud 기반 오픈 Anchor 개발’ ..",
    href: "https://www.newswire.co.kr/newsRead.php?no=936572",
    image: "/assets/news/news-0119.jpg",
  },
  {
    id: 118,
    outlet: "비디오플러스",
    date: "2020.07.01",
    title: "제머나이소프트, GS인증 1등급 3관왕 달성",
    summary: "제머나이소프트가 최근 자체 개발한 미디어 관리 전문 솔루션 3종이 최근 잇달아 GS(Good Software)인증 1등급을 획득했다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106621%26pagecnt%3D0%26letter_no%3D13%26offset%3D0%26search%3Dname%26searchstring%3D%C1%A6%B8%D3%B3%AA%C0%CC%BC%D2%C7%C1%C6%AE%26present_num%3D13&amp;boardIndex=1&amp;serin=1",
    image: "/assets/news/news-0118.jpg",
  },
  {
    id: 117,
    outlet: "디지털경제뉴스",
    date: "2020.06.04",
    title: "제머나이소프트 3개 제품 GS인증 1등급 획득",
    summary: "제머나이소프트의 미디어 관리 전문 솔루션 3종이 최근 GS(Good Software) 인증 1등급을 잇달아 획득했다.",
    href: "http://www.denews.co.kr/news/articleView.html?idxno=13660",
    image: "/assets/news/news-0117.png",
  },
  {
    id: 116,
    outlet: "디지털데일리",
    date: "2020.06.03",
    title: "제머나이소프트, 미디어 관리 솔루션 3종 GS 1등급 획득",
    summary: "제머나이소프트는 자체 개발한 미디어 관리 전문 솔루션 3종이 굿소프트웨어(GS) 인증 1등급을 획득했다고 3일 밝혔다.",
    href: "https://www.ddaily.co.kr/news/article/?no=196447",
    image: "/assets/news/news-0116.png",
  },
  {
    id: 115,
    outlet: "비디오아트",
    date: "2020.06.03",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 성공적 구축",
    summary: "제머나이소프트(대표 강진욱, www.gemiso.co.kr)는 재단법인 가톨릭평화방송(대표 조정래, www.cpbc.co.kr, 이하 가톨릭평화방송)의 TV 제작 HD(High Definition) 전환에 따른 통합 시스템을 성공적으로 구축 완료했다고 발표했다.",
    href: "https://www.videoarts.co.kr/customer/news_view.php?bd_id=2704&amp;page=1&amp;s_start=&amp;s_end=&amp;s_cate=01&amp;s_value=&amp;end_no=10",
    image: "/assets/news/news-0115.jpg",
  },
  {
    id: 114,
    outlet: "정보통신신문",
    date: "2020.06.03",
    title: "제머나이소프트, 국산 미디어관리솔루션 두각",
    summary: "제머나이소프트가 자체 개발한 미디어관리솔루션 3종이 최근 잇달아 GS(Good Software)인증 1등급을 획득했다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=78951",
    image: "/assets/news/news-0114.jpg",
  },
  {
    id: 113,
    outlet: "디지털투데이",
    date: "2020.06.02",
    title: "제머나이소프트, 이미지관리 솔루션으로도 GS 인증 획득",
    summary: "디지털 미디어 관리 플랫폼 업체 제머나이소프트(대표 강진욱, www.gemiso.co.kr)가 자체 개발한 이미지 관리 전문 솔루션 ‘에어리얼 이미지 아카이브(Ariel Image Archive)’가 굿소프트웨어(Good Software: GS)인증 1등급을 받았다고 3일 밝혔다.",
    href: "http://www.digitaltoday.co.kr/news/articleView.html?idxno=236772",
    image: "/assets/news/news-0113.jpg",
  },
  {
    id: 112,
    outlet: "DATANET",
    date: "2020.06.02",
    title: "제머나이소프트, 미디어 관리 솔루션 3종 ‘GS인증 1등급’ 획득",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)는 자체 개발 미디어 관리 전문 솔루션 3종이 최근 잇달아 GS(Good Software)인증 1등급을 획득했다고 3일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=146662",
    image: "/assets/news/news-0112.png",
  },
  {
    id: 111,
    outlet: "전자신문",
    date: "2020.06.02",
    title: "제머나이소프트, 미디어 관리 3종 솔루션 잇달아 GS인증 1등급 획득",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)가 자체 개발한 미디어 관리 전문 솔루션 3종이 최근 잇달아 GS(Good Software)인증 1등급을 획득했다고 밝혔다.",
    href: "https://www.etnews.com/20200603000242",
    image: "/assets/news/news-0111.jpg",
  },
  {
    id: 110,
    outlet: "아이티비즈",
    date: "2020.06.02",
    title: "제머나이소프트, 미디어 관리 전문 솔루션 3종 GS인증 1등급 획득",
    summary: "제머나이소프트(대표 강진욱)가 자체 개발한 미디어 관리 전문 솔루션 3종이 최근 잇달아 GS(Good Software)인증 1등급을 획득했다고 3일 밝혔다.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=41060",
    image: "/assets/news/news-0110.jpg",
  },
  {
    id: 109,
    outlet: "방송과기술",
    date: "2020.05.30",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 성공적 구축",
    summary: "제머나이소프트가 가톨릭평화방송의 TV 제작 HD 전환에 따른 통합 시스템을 성공적으로 구축 완료했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_0907e3abe4b641729f4d69d06ca12eec.pdf",
    image: "/assets/news/news-0109.jpg",
  },
  {
    id: 108,
    outlet: "비디오플러스",
    date: "2020.05.30",
    title: "제머나이소프트, 방송 제작에서 편집 및 전송까지 원스톱 워크플로 통합 시스템",
    summary: "제머나이소프트는 최근 재단법인 가톨릭평화방송의 TV제작 HD 전환에 따른 통합 시스템을 성공적으로 구축 완료했다고 발표했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_c74525eb86664619982068a1cb367c24.pdf",
    image: "/assets/news/news-0108.jpg",
  },
  {
    id: 107,
    outlet: "DATANET",
    date: "2020.05.06",
    title: "제머나이, 가톨릭평화방송 HD 통합 시스템 구축",
    summary: "제머나이소프트(대표 강진욱)는 가톨릭평화방송(대표 조정래)의 TV 제작 HD(High Definition) 전환에 따른 통합 시스템을 성공적으로 구축했다고 7일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=145576",
    image: "/assets/news/news-0107.jpg",
  },
  {
    id: 106,
    outlet: "아이티비즈",
    date: "2020.05.06",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 구축완료",
    summary: "제머나이소프트(대표 강진욱)는 가톨릭평화방송(대표 조정래)의 TV 제작 HD(High Definition) 전환에 따른 통합 시스템을 성공적으로 구축 완료했다고 7일 발표했다.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=40341",
    image: "/assets/news/news-0106.jpg",
  },
  {
    id: 105,
    outlet: "IT World",
    date: "2020.05.06",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 구축 완료",
    summary: "제머나이소프트(www.gemiso.co.kr)는 가톨릭평화방송(www.cpbc.co.kr)의 TV 제작 HD(High Definition) 전환에 따른 통합 시스템을 성공적으로 구축 완료했다고 발표했다.",
    href: "https://www.itworld.co.kr/news/151952",
    image: "/assets/news/news-0105.jpg",
  },
  {
    id: 104,
    outlet: "블로터",
    date: "2020.05.06",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트(대표 강진욱)는 재단법인 가톨릭평화방송(대표 조정래, 이하 가톨릭평화방송)이 추진하는 TV 제작 HD(High Definition) 전환에 따른 통합 시스템 구축 프로젝트를 완료했다고 5월7일 밝혔다.",
    href: "https://www.bloter.net/newsView/blt202005070012",
    image: "/assets/news/news-0104.jpg",
  },
  {
    id: 103,
    outlet: "정보통신신문",
    date: "2020.05.06",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 구축",
    summary: "제머나이소프트는 가톨릭평화방송의 TV 제작 HD 전환에 따른 통합 시스템을 성공적으로 구축 완료했다고 7일 밝혔다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=78774",
    image: "/assets/news/news-0103.jpg",
  },
  {
    id: 102,
    outlet: "전자신문",
    date: "2020.05.05",
    title: "제머나이소프트, 가톨릭평화방송 HD 통합 시스템 구축",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)는 가톨릭평화방송(대표 조정래) TV 제작 HD(High Definition) 전환에 따른 통합 시스템을 성공적으로 구축 완료했다고 발표했다.",
    href: "https://www.etnews.com/20200507000212",
    image: "/assets/news/news-0102.jpg",
  },
  {
    id: 101,
    outlet: "방송과기술",
    date: "2020.04.01",
    title: "제머나이소프트 GPU 트랜스코더, GS인증 1등급 획득",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트의 트랜스코더 제품인 ‘에어리얼(Ariel) GPU 트랜스코더’가 최근 GS(Good Software)인증 1등급을 획득했다.",
    href: "http://tech.kobeta.com/%ec%a0%9c%eb%a8%b8%eb%82%98%ec%9d%b4%ec%86%8c%ed%94%84%ed%8a%b8-gpu-%ed%8a%b8%eb%9e%9c%ec%8a%a4%ec%bd%94%eb%8d%94-gs%ec%9d%b8%ec%a6%9d-1%eb%93%b1%ea%b8%89-%ed%9a%8d%eb%93%9d/",
    image: "/assets/news/news-0101.png",
  },
  {
    id: 100,
    outlet: "비디오플러스",
    date: "2020.03.14",
    title: "제머나이소프트, GPU 트랜스코더가 GS인증 1등급 획득",
    summary: "제머나이소프트는 최근 자사의 트랜스코더 제품인 ‘에어리얼(Ariel) GPU 트랜스코더’가 GS(Good Software)인증 1등급을 획득했다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106523%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0100.png",
  },
  {
    id: 99,
    outlet: "비디오플러스",
    date: "2020.01.07",
    title: "제머나이소프트, 글로벌 우수 성과 ‘과기정통부장관’ 표창",
    summary: "제머나이소프트가 지난 2019년 정보통신방송사업 성과보고회에서 글로벌 우수 성과 창출 기업으로 선정, 과학기술정보통신부장관상을 수상했다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106396%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0099.jpg",
  },
  {
    id: 98,
    outlet: "방송과기술",
    date: "2020.01.05",
    title: "제머나이소프트, 글로벌 우수 성과 ‘과기정통부장관’ 표창",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 2019년 정보통신방송사업 성과보고회에서 글로벌 우수 성과 창출 기업으로 선정, 과학기술정보통신부 장관상을 수상했다.",
    href: "http://tech.kobeta.com/%ec%a0%9c%eb%a8%b8%eb%82%98%ec%9d%b4%ec%86%8c%ed%94%84%ed%8a%b8-%ea%b8%80%eb%a1%9c%eb%b2%8c-%ec%9a%b0%ec%88%98-%ec%84%b1%ea%b3%bc-%ea%b3%bc%ea%b8%b0%ec%a0%95%ed%86%b5%eb%b6%80%ec%9e%a5/",
    image: "/assets/news/news-0098.jpg",
  },
  {
    id: 97,
    outlet: "전자신문",
    date: "2019.12.10",
    title: "[ICT 산업 마중물, 정보통신방송사업] 〈1〉중소·벤처기업, 글로벌 도약 날개 달아",
    summary: "제머나이소프트는 개발도상국 방송 환경을 개선하고 국내 방송 산업 국제적 기반 확대를 위해 추진중인'개도국 방송환경 개선지원' 사업에 참여했다.",
    href: "https://www.etnews.com/20191211000072",
    image: "/assets/news/news-0097.jpg",
  },
  {
    id: 96,
    outlet: "아이뉴스24",
    date: "2019.12.10",
    title: "KCA, '2019년 정보통신방송사업 성과보고회' 개최",
    summary: "KCA가 올해 정보통신방송사업 성과보고회를 개최했다.",
    href: "https://www.inews24.com/view/1228502",
    image: "/assets/news/news-0096.jpg",
  },
  {
    id: 95,
    outlet: "DATANET",
    date: "2019.09.08",
    title: "강진욱 제머나이소프트 대표 '미디어 전문 기술력 기반 신사업 확대'",
    summary: "국내를 넘어 해외 시장으로도 영향력 넓히기 위해 전념하고 있는 제머나이소프트를 찾아 자세한 이야기를 들어봤다. 다음은 강진욱 제머나이소프트 대표이사와의 일문일답.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=137201",
    image: "/assets/news/news-0095.jpg",
  },
  {
    id: 94,
    outlet: "DATANET",
    date: "2019.09.08",
    title: "제머나이소프트 '글로벌 디지털 미디어 솔루션 기업으로 도약'",
    summary: "탄탄한 기술력 기반 영상 특화 솔루션 확대...전문 배포 서비스 모델도 추진",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=137198",
    image: "/assets/news/news-0094.jpg",
  },
  {
    id: 93,
    outlet: "비디오플러스",
    date: "2019.09.03",
    title: "제머나이소프트 대표 강진욱 '국내를 넘어 해외로 진출하다'",
    summary: "하나의 영상이 완성되기 위해서는 촬영뿐만 아니라 편집, 송출 등 각 분야의 시스템이 유기적으로 연결돼야 한다. 제머나이소프트는 이를 효율적으로 관리하는 국내 전문 기업이다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106155%26pagecnt%3D0%26letter_no%3D25%26offset%3D0%26search%3D%26searchstring%3D%26present_num%3D24&amp;boardIndex=28&amp;pc=",
    image: "/assets/news/news-0093.jpg",
  },
  {
    id: 92,
    outlet: "비디오플러스",
    date: "2019.08.08",
    title: "제머나이소프트, 광주MBC 보도 제작 시스템 구축 완료",
    summary: "제머나이소프트는 최근 광주문화방송의 네트워크 기반 제작 시스템(Network Production System: NPS)을 성공적으로 구축 완료했다고 밝혔다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106108%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0092.png",
  },
  {
    id: 91,
    outlet: "방송기술저널",
    date: "2019.07.23",
    title: "제머나이소프트, 광주MBC 보도 제작 시스템 구축 완료",
    summary: "제머나이소프트가 MBC에 이어 광주 MBC에도 네트워크 기반 제작 시스템(Network Production System, 이하 NPS)을 구축했다.",
    href: "http://journal.kobeta.com/%ec%a0%9c%eb%a8%b8%eb%82%98%ec%9d%b4%ec%86%8c%ed%94%84%ed%8a%b8-%ea%b4%91%ec%a3%bcmbc-%eb%b3%b4%eb%8f%84-%ec%a0%9c%ec%9e%91-%ec%8b%9c%ec%8a%a4%ed%85%9c-%ea%b5%ac%ec%b6%95-%ec%99%84%eb%a3%8c/",
    image: "/assets/news/news-0091.png",
  },
  {
    id: 90,
    outlet: "전자신문",
    date: "2019.07.22",
    title: "제머나이소프트, 광주MBC 보도제작 시스템 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)가 광주문화방송(대표 송일준, 이하 광주MBC) 네트워크 기반 제작 시스템(Network Production System: NPS)을 구축 완료했다고 23일 발표했다.",
    href: "https://www.etnews.com/20190723000322",
    image: "/assets/news/news-0090.png",
  },
  {
    id: 89,
    outlet: "IT조선",
    date: "2019.07.22",
    title: "제머나이소프트, 광주MBC에 네트워크 기반 보도 제작 시스템 구축",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트가 광주문화방송(이하 광주MBC)에 자사의 네트워크 기반 제작 시스템(Network Production System: NPS)의 구축을 완료했다고 23일 밝혔다.",
    href: "http://it.chosun.com/site/data/html_dir/2019/07/23/2019072301167.html",
    image: "/assets/news/news-0089.png",
  },
  {
    id: 88,
    outlet: "DATANET",
    date: "2019.07.22",
    title: "제머나이소프트, 광주MBC 보도 제작 시스템 구축 완료",
    summary: "제머나이소프트(대표 강진욱)는 광주문화방송(이하 광주MBC, 대표 송일준)의 네트워크 기반 제작 시스템(NPS: Network Production System)을 성공적으로 구축 완료했다고 23일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=135846",
    image: "/assets/news/news-0088.png",
  },
  {
    id: 87,
    outlet: "아이티비즈",
    date: "2019.07.22",
    title: "제머나이소프트, 광주MBC 보도 제작 시스템 구축 완료",
    summary: "제머나이소프트(대표 강진욱)가 광주문화방송(대표 송일준)의 네트워크 기반 제작 시스템(NPS)을 구축 완료했다고 23일 발표했다.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=32180",
    image: "/assets/news/news-0087.png",
  },
  {
    id: 86,
    outlet: "디지털데일리",
    date: "2019.07.22",
    title: "제머나이소프트, 광주MBC 보도제작시스템 구축",
    summary: "제머나이소프트(대표 강진욱)는 광주문화방송(이하 광주MBC)의 네트워크 기반 제작 시스템(NPS)을 구축 완료했다고 23일 밝혔다.",
    href: "https://www.ddaily.co.kr/news/article/?no=183840",
    image: "/assets/news/news-0086.png",
  },
  {
    id: 85,
    outlet: "반도체네트워크",
    date: "2019.06.18",
    title: "Different, Scalable and Fast UHD Transcoding 10min 'Proxima'",
    summary: "Different, Scalable and Fast UHD Transcoding 10min “Proxima”",
    href: "https://www.seminet.co.kr/channel_micro.html?menu=video_sub&amp;com_no=817&amp;video_id=9885&amp;cate_no=33&amp;cate_name=Exhibition",
    image: "/assets/news/news-0085.jpg",
  },
  {
    id: 84,
    outlet: "비디오아트",
    date: "2019.05.30",
    title: "KOBA 2019",
    summary: "Special Issue/KOBA 2019",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_1cd9b9469b6d493e8c27fbec990260f1.pdf",
    image: "/assets/news/news-0084.jpg",
  },
  {
    id: 83,
    outlet: "비디오플러스",
    date: "2019.05.30",
    title: "미디어, 선택을 만들다-KOBA 2019",
    summary: "KOBA 2019 주요 참가 업체",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_60d22cf3dd0e4040bf140e1375784a04.pdf",
    image: "/assets/news/news-0083.jpg",
  },
  {
    id: 82,
    outlet: "방송과기술",
    date: "2019.05.30",
    title: "제머나이소프트, MBC 보도 NPS ‘NPS·M’ 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 MBC의 뉴스 제작 워크플로우를 고도화하는 보도 NPS인 ‘NPS·M’ 구축 프로젝트를 성공적으로 완료했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_85011b93c7e4414e9edc9d3e8b652f30.pdf",
    image: "/assets/news/news-0082.png",
  },
  {
    id: 81,
    outlet: "Nextdaily",
    date: "2019.05.30",
    title: "폭증하는 미디어 데이터, 돈이 되는 최적 관리법은?",
    summary: "데이터의 생성부터 소멸까지 전 생애주기를 관리해주는 제머나이소프트의 미디어 자산 관리(MAM) 솔루션이 미디어 자산관리에 어려움을 겪고 있는 기업들에게 최적의 답을 제시하고 있다.",
    href: "http://www.nextdaily.co.kr/news/articleView.html?idxno=76286",
    image: "/assets/news/news-0081.png",
  },
  {
    id: 80,
    outlet: "IT Daily",
    date: "2019.05.19",
    title: "제머나이소프트, MAM 솔루션에 클라우드 오브젝트 스토리지 연동",
    summary: "제머나이소프트(대표 강진욱)는 자사 미디어 자산 관리(MAM) 솔루션에 클라우드 오브젝트 스토리지를 연동해 보다 향상된 기능을 제공하게 됐다고 20일 밝혔다.",
    href: "http://www.itdaily.kr/news/articleView.html?idxno=94813",
    image: "/assets/news/news-0080.png",
  },
  {
    id: 79,
    outlet: "정보통신신문",
    date: "2019.05.19",
    title: "[KOBA 2019] 기술력으로 중무장한 국산 방송장비 ‘봇물’",
    summary: "[제머나이소프트] 보안성 크게 높인 MAM시스템 공개",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=75584",
    image: "/assets/news/news-0079.png",
  },
  {
    id: 78,
    outlet: "전자신문",
    date: "2019.05.19",
    title: "제머나이소프트, 오브젝트 스토리지 연동 ‘클라우드 미디어 관리 솔루션’ 선봬",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)가 오는 5월 22일부터 25일까지 4일간 열리는 ‘제29회 국제 방송•음향•조명기기 전시회(KOBA 2019)’에서 클라우드 기반으로 자사의 미디어 자산 관리(Media Asset Management 이하 MAM) 솔루션과 연동한 오브젝트 스토리지 솔루션을 선보인다고 밝혔다.",
    href: "https://www.etnews.com/20190520000139",
    image: "/assets/news/news-0078.png",
  },
  {
    id: 77,
    outlet: "테크월드",
    date: "2019.05.19",
    title: "제머나이소프트, 오브젝트 스토리지 연동한 MAM 솔루션 공개",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트(Gemiso)가 자사의 오브젝트 스토리지를 연동안 미디어 자산 관리(MAM) 솔루션을 발표했다.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=90413",
    image: "/assets/news/news-0077.png",
  },
  {
    id: 76,
    outlet: "DATANET",
    date: "2019.05.19",
    title: "제머나이, 오브젝트 스토리지 연동 미디어 관리 솔루션 선봬",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트(대표 강진욱)는 자사의 미디어 자산 관리(MAM) 솔루션과 오브젝트 스토리지를 연동한 시스템을 출시한다고 20일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=134041",
    image: "/assets/news/news-0076.png",
  },
  {
    id: 75,
    outlet: "비디오플러스",
    date: "2019.03.21",
    title: "제머나이소프트, MBC 보도 NPS ‘NPS·M’ 구축 완료",
    summary: "제머나이소프트는 최근 MBC의 뉴스 제작 워크플로를 고도화하는 보도 NPS(Network Production System)인 NPS·M 구축 프로젝트를 성공적으로 완료했다고 발표했다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105687%26pagecnt%3D0%26letter_no%3D606%26offset%3D0%26search%3D%26searchstring%3D%26present_num%3D602&amp;boardIndex=1&amp;pc=",
    image: "/assets/news/news-0075.png",
  },
  {
    id: 74,
    outlet: "정보통신신문",
    date: "2019.03.19",
    title: "제머나이소프트, MBC 보도 제작 시스템 구축 완료",
    summary: "제머나이소프트(대표 강진욱)가 MBC의 뉴스 제작 워크플로우를 고도화하는 보도 네트워크기반제작시스템(NPS: Network Production System)인 ‘NPS·M’ 구축 프로젝트를 성공적으로 완료했다고 발표했다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74951",
    image: "/assets/news/news-0074.png",
  },
  {
    id: 73,
    outlet: "전자신문",
    date: "2019.03.18",
    title: "제머나이소프트, MBC 제작·보도 시스템 ‘NPS·M’ 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트(대표 강진욱)가 MBC(대표 최승호)의 뉴스 제작 워크플로를 고도화하는 보도 NPS(Network Production System, 네트워크 기반 제작 시스템)인 ‘NPS·M’ 구축 프로젝트를 성공적으로 완료했다고 발표했다.",
    href: "https://www.etnews.com/20190319000265",
    image: "/assets/news/news-0073.png",
  },
  {
    id: 72,
    outlet: "아이티비즈",
    date: "2019.03.18",
    title: "제머나이소프트, MBC 보도 NPS ‘NPSㆍM’ 구축 완료",
    summary: "제머나이소프트(대표 강진욱)가 MBC(대표 최승호)의 뉴스 제작 워크플로를 고도화하는 보도 NPS(Network Production System)인 ‘NPSㆍM’ 구축 프로젝트를 성공적으로 완료했다고 19일 발표했다.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=29015",
    image: "/assets/news/news-0072.png",
  },
  {
    id: 71,
    outlet: "디지털데일리",
    date: "2019.03.18",
    title: "제머나이소프트, MBC 보도 제작시스템 고도화",
    summary: "제머나이소프트(대표 강진욱)는 MBC의 뉴스 제작 과정을 고도화하는 보도 NPS(Network Production System) ‘NPS·M’ 구축 프로젝트를 성공적으로 완료했다고 19일 밝혔다.",
    href: "https://www.ddaily.co.kr/news/article/?no=179043",
    image: "/assets/news/news-0071.png",
  },
  {
    id: 70,
    outlet: "DATANET",
    date: "2019.03.18",
    title: "제머나이소프트, MBC 뉴스 보도 NPS 구축 완료",
    summary: "제머나이소프트(대표 강진욱)는 MBC(대표 최승호)의 보도 NPS(Network Production System)인 ‘NPS·M’ 구축 프로젝트를 성공적으로 완료했다고 19일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=132060",
    image: "/assets/news/news-0070.png",
  },
  {
    id: 69,
    outlet: "비디오아트",
    date: "2019.02.27",
    title: "제머나이소프트, 라디오 파키스탄에 '이모션'구축",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트(대표 강진욱, www.gemiso.co.kr)가 라디오 파키스탄 물탄(www.radio.gov.pk)에 라디오 방송 전문 솔루션 '이모션(E.moti.on)'을 성공적으로 구축 완료했다고 밝혔다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_c262041a58c248cfa6152bb9ddf2b1cb.pdf",
    image: "/assets/news/news-0069.jpg",
  },
  {
    id: 68,
    outlet: "비디오플러스",
    date: "2019.02.27",
    title: "제머나이소프트, 라디오 파키스탄에 ‘이모션’ 구축 완료",
    summary: "제머나이소프트는 최근 라디오 파키스탄 물탄(www.radio.gov.pk)에 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’을 구축했다고 발표했다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105642%26pagecnt%3D0%26letter_no%3D590%26offset%3D0%26search%3D%26searchstring%3D%26present_num%3D585&amp;boardIndex=1&amp;pc=",
    image: "/assets/news/news-0068.jpg",
  },
  {
    id: 67,
    outlet: "정보통신신문",
    date: "2019.02.26",
    title: "제머나이소프트, 파키스탄에 라디오 방송 솔루션 공급",
    summary: "제머나이소프트(대표 강진욱)가 파키스탄 국영 라디오 방송국에 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’을 성공적으로 구축했다고 발표했다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74818",
    image: "/assets/news/news-0067.jpg",
  },
  {
    id: 66,
    outlet: "DATANET",
    date: "2019.02.25",
    title: "제머나이, 라디오 파키스탄에 ‘이모션’ 구축",
    summary: "제머나이소프트(대표 강진욱)는 라디오 파키스탄 물탄에 라디오 방송 전문 솔루션 ‘이모션’을 구축했다고 26일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=131415",
    image: "/assets/news/news-0066.jpg",
  },
  {
    id: 65,
    outlet: "전자신문",
    date: "2019.02.25",
    title: "국산 라디오 방송 솔루션 제머나이소프트 ’이모션’ 파키스탄 진출",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)가 라디오 파키스탄 물탄에 라디오 방송 전문 솔루션 ‘이모션’을 성공적으로 구축 완료했다고 발표했다.",
    href: "https://www.etnews.com/20190226000397",
    image: "/assets/news/news-0065.jpg",
  },
  {
    id: 64,
    outlet: "IT조선",
    date: "2019.02.25",
    title: "제머나이소프트, 라디오 파키스탄에 ‘이모션’ 구축",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트는 라디오 파키스탄 물탄에 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’을 성공적으로 구축했다고 26일 밝혔다.",
    href: "http://it.chosun.com/site/data/html_dir/2019/02/26/2019022601401.html",
    image: "/assets/news/news-0064.jpg",
  },
  {
    id: 63,
    outlet: "테크월드",
    date: "2019.02.25",
    title: "제머나이소프트, 파키스탄 국영 라디오 방송국에 ‘이모션’ 라디오 솔루션 구축",
    summary: "제머나이소프트가 라디오 파키스탄 물탄에 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’을 성공적으로 구축 완료했다고 발표했다.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=82600",
    image: "/assets/news/news-0063.jpg",
  },
  {
    id: 62,
    outlet: "방송과기술",
    date: "2018.11.29",
    title: "'이모션' 2018 전파방송기술대상 국무총리상 수상",
    summary: "EBS가 개발한 라디오 제작 송출 솔루션 '이모션(E.moti.on)'이 '전파방송기술대상'에서 국무총리상을 수상했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_d67cc1eab4314cc9afe15e28839659a9.pdf",
    image: "/assets/news/news-0062.jpg",
  },
  {
    id: 61,
    outlet: "비디오아트",
    date: "2018.11.29",
    title: "EBS-제머나이소프트 협력 라디오 방송 솔루션 '이모션'기술력 공식 인정",
    summary: "한국교육방송공사(이하 EBS, 대표 장해랑)가 개발하고 제머나이소프트(대표 강진욱)가 공급하는 라디오 방송 전문 솔루션 '이모션(E.moti.on)'이 '2018 전파방송기술대상' 국무총리상을 수상했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_5781d9a763ab442bac92692913c18b27.pdf",
    image: "/assets/news/news-0061.jpg",
  },
  {
    id: 60,
    outlet: "비디오플러스",
    date: "2018.11.22",
    title: "이모션, 전파방송기술대상 국무총리상 수상",
    summary: "EBS가 개발하고 제머나이소프트가 공급하는 라디오 방송 전문 솔루션 이모션(E,moti.on)이 2018 전파방송기술대상 국무총리상을 수상했다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105361%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0060.jpg",
  },
  {
    id: 59,
    outlet: "정보통신신문",
    date: "2018.11.20",
    title: "제머나이소프트, 라디오방송 솔루션 국무총리상 수상",
    summary: "한국교육방송공사(EBS)가 개발하고 제머나이소프트(대표 강진욱)가 공급한 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’이 ‘2018 전파방송기술대상’ 국무총리상을 수상했다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74251",
    image: "/assets/news/news-0059.jpg",
  },
  {
    id: 58,
    outlet: "전자신문",
    date: "2018.11.20",
    title: "라디오방송 솔루션 '이모션' 전파방송기술대상 국무총리상 수상",
    summary: "한국교육방송공사(이하 EBS, 대표 장해랑)가 개발하고 제머나이소프트(대표 강진욱)가 공급하는 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’이 ‘2018 전파방송기술대상’ 국무총리상을 수상했다.",
    href: "https://www.etnews.com/20181120000416",
    image: "/assets/news/news-0058.jpg",
  },
  {
    id: 57,
    outlet: "DATANET",
    date: "2018.11.19",
    title: "EBS·제머나이 '이모션', 전파방송기술대상 국무총리상 수상",
    summary: "한국교육방송공사(이하 EBS, 대표 장해랑)가 개발하고 제머나이소프트(대표 강진욱)가 공급하는 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’이 ‘2018 전파방송기술대상’ 국무총리상을 수상했다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=128535",
    image: "/assets/news/news-0057.jpg",
  },
  {
    id: 56,
    outlet: "IT조선",
    date: "2018.11.19",
    title: "제머나이소프트 '이모션', 전파방송기술 대상 국무총리상 수상",
    summary: "제머나이소프트는 라디오 방송 솔루션 ‘이모션(E.moti.on)’이 ‘2018 전파방송기술대상’ 국무총리상을 수상했다고 20일 밝혔다.",
    href: "http://it.chosun.com/site/data/html_dir/2018/11/20/2018112001924.html",
    image: "/assets/news/news-0056.jpg",
  },
  {
    id: 55,
    outlet: "아이티비즈",
    date: "2018.11.19",
    title: "EBS-제머나이소프트 '이모션', 전파방송기술대상 국무총리상 수상",
    summary: "한국교육방송공사(대표 장해랑, EBS)가 개발하고 제머나이소프트(대표 강진욱)가 공급하는 라디오 방송 전문 솔루션 ‘이모션’이 ‘2018 전파방송기술대상’ 국무총리상을 수상했다.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=25879",
    image: "/assets/news/news-0055.jpg",
  },
  {
    id: 54,
    outlet: "방송과기술",
    date: "2018.11.04",
    title: "㈜제머나이소프트, 경기도의회 영상∙사진 디지털 변환 및 아카이브를 위한 MAM 시스템 구축",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 경기도의회(www.ggc.go.kr)의 영상∙사진 아카이브 시스템을 성공적으로 구축 완료했다.",
    href: "http://tech.kobeta.com/%E3%88%9C%EC%A0%9C%EB%A8%B8%EB%82%98%EC%9D%B4%EC%86%8C%ED%94%84%ED%8A%B8-%EA%B2%BD%EA%B8%B0%EB%8F%84%EC%9D%98%ED%9A%8C-%EC%98%81%EC%83%81%E2%88%99%EC%82%AC%EC%A7%84-%EB%94%94%EC%A7%80%ED%84%B8/",
    image: "/assets/news/news-0054.jpg",
  },
  {
    id: 53,
    outlet: "비디오아트",
    date: "2018.10.30",
    title: "중소 규모 미디어 아카이브 시스템을 위한 솔루션, Proxima",
    summary: "미디어 아카이브 시스템은 사진, 음악, 영상 등 미디어들을 오랫동안 보관하고, 보관된 미디어들을 신속하게 찾아서 재활용할 수 있도록 도와주는 시스템이다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_501b02d3fcd84c8fb0bf57ceb71ebf1c.pdf",
    image: "/assets/news/news-0053.png",
  },
  {
    id: 52,
    outlet: "정보통신신문",
    date: "2018.10.28",
    title: "강진욱 제머나이소프트 대표, “수요처가 인정하는 MAM 선두주자 될 터”",
    summary: "토종 기술로 아카이브 시장에서 두각을 나타내고 있는 기업이 제머나이소프트다. 강진욱 대표는 특히 사진·영상 등 대용량 멀티미디어에 대한 아카이빙 수요가 증가하고 있다고 말한다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74116",
    image: "/assets/news/news-0052.png",
  },
  {
    id: 51,
    outlet: "비디오플러스",
    date: "2018.10.17",
    title: "제머나이소프트, 경기도의회 영상·사진 아카이브 시스템 구축",
    summary: "제머나이소프트는 최근 경기도의회의 영상·사진 아카이브 시스템을 성공적으로 구축했다고 밝혔다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105265%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0051.jpg",
  },
  {
    id: 50,
    outlet: "전자신문",
    date: "2018.10.15",
    title: "제머나이소프트, 경기도의회 아카이브 시스템 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 기업인 제머나이소프트(대표 강진욱)가 경기도의회의 영상∙사진 아카이브 시스템을 성공적으로 구축 완료했다고 발표했다.",
    href: "https://www.etnews.com/20181015000419",
    image: "/assets/news/news-0050.jpg",
  },
  {
    id: 49,
    outlet: "정보통신신문",
    date: "2018.10.15",
    title: "제머나이소프트, 경기도의회 아카이브 시스템 구축 완료",
    summary: "제머나이소프트(대표 강진욱)가 경기도의회(www.ggc.go.kr)의 영상·사진 아카이브 시스템을 성공적으로 구축 완료했다고 15일 밝혔다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74038",
    image: "/assets/news/news-0049.jpg",
  },
  {
    id: 48,
    outlet: "IT Daily",
    date: "2018.10.14",
    title: "제머나이소프트, 경기도의회 아카이브 시스템 구축 성료",
    summary: "제머나이소프트(대표 강진욱)는 경기도의회의 영상·사진 아카이브 시스템 구축사업을 성공리에 마쳤다고 15일 밝혔다.",
    href: "http://www.itdaily.kr/news/articleView.html?idxno=91314",
    image: "/assets/news/news-0048.jpg",
  },
  {
    id: 47,
    outlet: "IT조선",
    date: "2018.10.14",
    title: "제머나이소프트, 경기도의회 아카이브 시스템 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트는 경기도의회 영상∙사진 아카이브 시스템을 구축했다고 15일 밝혔다. 이에 따라 경기도의회는 오래된 영상∙사진 자료를 모두 디지털화하고 하나의 시스템으로 이관함으로써, 약 65만건에 달하는 모든 영상∙사진 자료를 통합 관리하고 운영하게 됐다.",
    href: "http://it.chosun.com/site/data/html_dir/2018/10/15/2018101502182.html",
    image: "/assets/news/news-0047.jpg",
  },
  {
    id: 46,
    outlet: "DATANET",
    date: "2018.10.14",
    title: "제머나이소프트, 경기도의회 아카이브 시스템 구축 완료",
    summary: "제머나이소프트(대표 강진욱)는 경기도의회의 영상·사진 아카이브 시스템을 성공적으로 구축 완료했다고 15일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=127322",
    image: "/assets/news/news-0046.jpg",
  },
  {
    id: 45,
    outlet: "ZDNet",
    date: "2018.10.14",
    title: "제머나이, 경기도의회 아카이브 시스템 구축 완료",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)는 경기도 의회의 영상 및 사진 아카이브 시스템을 성공적으로 구축, 완료했다고 15일 밝혔다.",
    href: "https://zdnet.co.kr/view/?no=20181015215436",
    image: "/assets/news/news-0045.jpg",
  },
  {
    id: 44,
    outlet: "월간 PA",
    date: "2018.09.29",
    title: "중국 최대 비디오쇼핑업체 후이마이그룹과 에어리얼 기술 CMS 구축 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 중국 최대 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업인 베이징 후이마이 온라인 네트워크 과학 기술 유한회사에 콘텐츠 관리 시스템을 구축하기로 했다고 밝혔다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_efbd60f09e2e4a11968da5f2efbf5cd7.pdf",
    image: "/assets/news/news-0044.png",
  },
  {
    id: 43,
    outlet: "비디오플러스",
    date: "2018.09.29",
    title: "제머나이소프트, 개도국에 방송 솔루션 지원",
    summary: "제머나이소프트는 최근 한국전파진흥협회의 공적개발원조(ODA) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 밝혔다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_7ea712029bec4bdc89b9573c52f7c665.pdf",
    image: "/assets/news/news-0043.png",
  },
  {
    id: 42,
    outlet: "비디오아트",
    date: "2018.09.29",
    title: "제머나이소프트, 개도국에 방송 솔루션 지원",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트가 한국전파진흥협회의 공적개발원조 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 밝혔다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_783e8ca5c04c4f5fb9e82a5767af7042.pdf",
    image: "/assets/news/news-0042.png",
  },
  {
    id: 41,
    outlet: "방송과기술",
    date: "2018.09.29",
    title: "제머나이소프트, 한국전파진흥협회 ODA 사업 참여로 개도국에 방송 솔루션 지원",
    summary: "제머나이소프트가 한국전파진흥협회의 공적개발원조 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_0685c92fe92e4aed89d01f69e6e950cf.pdf",
    image: "/assets/news/news-0041.png",
  },
  {
    id: 40,
    outlet: "테크월드",
    date: "2018.09.09",
    title: "제머나이소프트, 개도국에 방송 솔루션 지원",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 한국전파진흥협회의 공적개발원조(Official Development Assistance : ODA) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 발표했다.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=80992",
    image: "/assets/news/news-0040.png",
  },
  {
    id: 39,
    outlet: "전자신문",
    date: "2018.09.09",
    title: "제머나이소프트, 에티오피아와 파키스탄에 방송 솔루션 구축",
    summary: "제머나이소프트(대표 강진욱)가 한국전파진흥협회의 공적개발원조(Official Development Assistance : ODA) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 발표했다.",
    href: "https://www.etnews.com/20180910000059",
    image: "/assets/news/news-0039.png",
  },
  {
    id: 38,
    outlet: "ZDNet",
    date: "2018.09.08",
    title: "제머나이소프트 '개도국에 방송 솔루션 지원'",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱)는 한국전파진흥협회의 공적개발원조(ODA:Official Development Assistance) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 9일 밝혔다.",
    href: "https://news.naver.com/main/read.naver?mode=LSD&amp;mid=sec&amp;oid=092&amp;aid=0002145602&amp;sid1=001",
    image: "/assets/news/news-0038.png",
  },
  {
    id: 37,
    outlet: "비디오플러스",
    date: "2018.09.06",
    title: "제머나이소프트, 개도국에 방송 솔루션 지원",
    summary: "제머나이소프트는 최근 한국전파진흥협회(RAPA)의 공적개발원조(ODA) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 밝혔다.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105168%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0037.png",
  },
  {
    id: 36,
    outlet: "디지털데일리",
    date: "2018.09.06",
    title: "제머나이소프트, 개도국에 방송 솔루션 지원",
    summary: "제머나이소프트(대표 강진욱)는 한국전파진흥협회의 공적개발원조(ODA) 사업에 참여, 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 7일 밝혔다.",
    href: "https://www.ddaily.co.kr/news/article/?no=172551",
    image: "/assets/news/news-0036.png",
  },
  {
    id: 35,
    outlet: "DATANET",
    date: "2018.09.06",
    title: "제머나이소프트, 에티오피아·파키스탄에 방송 솔루션 지원",
    summary: "제머나이소프트(대표 강진욱)는 한국전파진흥협회의 공적개발원조(ODA: Official Development Assistance) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 7일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=126272",
    image: "/assets/news/news-0035.png",
  },
  {
    id: 34,
    outlet: "IT 조선",
    date: "2018.09.06",
    title: "제머나이소프트, 에티오피아·파키스탄 등 개발도상국에 방송 솔루션 지원",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트는 한국전파진흥협회 공적개발원조(ODA) 사업에 참여해 에티오피아와 파키스탄에 자사 방송 솔루션을 공급한다고 7일 밝혔다.",
    href: "http://it.chosun.com/site/data/html_dir/2018/09/07/2018090702353.html",
    image: "/assets/news/news-0034.png",
  },
  {
    id: 33,
    outlet: "파이낸셜신문",
    date: "2018.09.06",
    title: "제머나이소프트, 에티오피아·파키스탄에 방송 솔루션 지원",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 한국전파진흥협회의 공적개발원조(Official Development Assistance : ODA) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다고 7일 발표했다.",
    href: "http://www.efnews.co.kr/news/articleView.html?idxno=76695",
    image: "/assets/news/news-0033.png",
  },
  {
    id: 32,
    outlet: "KINEWS",
    date: "2018.09.06",
    title: "제머나이소프트, 개도국에 방송 솔루션 지원",
    summary: "디지털 미디어 관리 플랫폼 기업인 제머나이소프트가 한국전파진흥협회의 공적개발원조(ODA) 사업에 참여해 에티오피아와 파키스탄에 자사의 방송 솔루션을 공급한다.",
    href: "",
    image: "/assets/news/news-0032.png",
  },
  {
    id: 31,
    outlet: "비디오아트",
    date: "2018.08.30",
    title: "제머나이소프트-中 후이마이그룹, CMS 구축 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트(대표 강진욱, www.gemiso.com)가 중국 최대의 비디오 쇼핑(홈쇼핑) 서비스 플랫폼 기업인 베이징 후이마이 온라인 네트워크 과학기술 유한회사에 콘텐츠 관리 시스템(CMS)을 구축하기로 했다고 밝혔다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_31b480e66de2433eb28fec206564ac2f.pdf",
    image: "/assets/news/news-0031.png",
  },
  {
    id: 30,
    outlet: "방송과기술",
    date: "2018.08.30",
    title: "제머나이소프트, 中 후이마이그룹 CMS 구축 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 중국 최대의 비디오쇼핑 서비스 플랫폼 기업인 베이징 후이마이 온라인 네트워크 과학기술 유한회사에 콘텐츠 관리 시스템을 구축한다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_519d94d20218480c81c65b475b95d52a.pdf",
    image: "/assets/news/news-0030.jpg",
  },
  {
    id: 29,
    outlet: "월간 PA",
    date: "2018.08.30",
    title: "현장 활용 기능 중심의 종합 방송 솔루션 '이모션'",
    summary: "한국교육방송공사가 개발하고 (주)제머나이소프트가 공급하는 이모션은 EBS의 오랜 방송 노하우와 자체 기술력으로 개발한 파일 기반 라디오 통합 시스템이다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_5e2bab6e29f24023a539121ce28b1c95.pdf",
    image: "/assets/news/news-0029.jpg",
  },
  {
    id: 28,
    outlet: "비디오플러스",
    date: "2018.08.30",
    title: "UHD MAM의 핵심 기술 '분산 처리'",
    summary: "제머나이소프트는 UHD 영상을 더욱 빠르고 효율적으로 구현할 수 있는 분산 트랜스코딩 기술을 한발 앞서 MAM 시스템에 도입했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_9874a46e5647436697f3045fba9ca1e9.pdf",
    image: "/assets/news/news-0028.png",
  },
  {
    id: 27,
    outlet: "비디오플러스",
    date: "2018.08.30",
    title: "제머나이소프트, 중국 후이마이그룹 CMS 구축 계약 체결",
    summary: "제머나이소프트는 최근 중국의 비디오쇼핑 서비스 플랫폼 기업인 베이징 후이마이 온라인 네트워크 과학기술 유한회사에 콘텐츠 관리 시스템을 구축하는 계약을 체결했다고 밝혔다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_4dc03e0e28264557a8c9694c66f8d315.pdf",
    image: "/assets/news/news-0027.png",
  },
  {
    id: 26,
    outlet: "전자신문",
    date: "2018.08.06",
    title: "중국 최대 홈쇼핑 플랫폼에 들어가는 국산 CMS ‘에어리얼’",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트(대표 강진욱)가 중국 최대 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업 베이징 후이마이 온라인 네트워크 과학기술 유한회사(이하 후이마이그룹, 대표 뚜뤠이용)에 콘텐츠 관리 시스템(Contents Management System : CMS)을 구축하기로 했다고 밝혔다.",
    href: "https://www.etnews.com/20180807000098",
    image: "/assets/news/news-0026.png",
  },
  {
    id: 25,
    outlet: "KINEWS",
    date: "2018.08.06",
    title: "제머나이소프트, 中 후이마이그룹 CMS 구축 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 기업인 제머나이소프트(대표 강진욱)가 중국 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업인 베이징후이마이온라인네트워크과학기술유한회사(이하 후이마이그룹)에 콘텐츠관리시스템(CMS)을 구축하기로 했다고 7일 밝혔다.",
    href: "",
    image: "/assets/news/news-0025.png",
  },
  {
    id: 24,
    outlet: "아이티비즈",
    date: "2018.08.06",
    title: "제머나이소프트, 中 후이마이그룹 콘텐츠관리시스템 구축한다",
    summary: "제머나이소프트(대표 강진욱)가 중국 비디오쇼핑 서비스 플랫폼 기업인 베이징 후이마이온라인 네트워크 과학기술 유한회사(후이마이그룹, 대표 뚜뤠이용)에 콘텐츠관리시스템(CMS)을 구축하기로 했다고 7일 밝혔다.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=23304",
    image: "/assets/news/news-0024.png",
  },
  {
    id: 23,
    outlet: "IT 조선",
    date: "2018.08.06",
    title: "제머나이소프트, 中 후이마이그룹 CMS 구축 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 기업 제머나이소프트는 중국 최대 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업 베이징 후이마이온라인 네트워크 과학기술 유한회사(이하 후이마이그룹)의 콘텐츠관리시스템(CMS)을 구축하는 계약을 체결했다고 7일 밝혔다.",
    href: "http://it.chosun.com/site/data/html_dir/2018/08/07/2018080701137.html",
    image: "/assets/news/news-0023.png",
  },
  {
    id: 22,
    outlet: "디지털데일리",
    date: "2018.08.06",
    title: "제머나이소프트, 中 후이마이그룹과 CMS 구축 계약 체결",
    summary: "제머나이소프트(대표 강진욱)는 중국 최대 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업인 후이마이그룹에 콘텐츠관리시스템(CMS) 구축 계약을 체결했다고 7일 밝혔다.",
    href: "https://www.ddaily.co.kr/news/article/?no=171432",
    image: "/assets/news/news-0022.png",
  },
  {
    id: 21,
    outlet: "DATANET",
    date: "2018.08.06",
    title: "제머나이소프트, 中 후이마이그룹과 CMS 구축 계약",
    summary: "제머나이소프트(대표 강진욱)는 중국 최대의 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업인 베이징 후이마이온라인 네트워크 과학기술 유한회사(이하 후이마이그룹, 대표 뚜뤠이용)에 콘텐츠 관리 시스템(CMS: Contents Management System)을 구축한다고 7일 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=125315",
    image: "/assets/news/news-0021.png",
  },
  {
    id: 20,
    outlet: "인터페이스뉴스",
    date: "2018.08.06",
    title: "제머나이소프트, 중 후이마이그룹 CMS 구축 시동",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트가 중국 최대의 비디오쇼핑(홈쇼핑) 서비스 플랫폼 기업인 베이징 후이마이온라인 네트워크 과학기술 유한회사(이하 후이마이그룹)에 콘텐츠 관리 시스템(ContentsManagement System : CMS)을 구축하기로 했다고 밝혔다.",
    href: "",
    image: "/assets/news/news-0020.png",
  },
  {
    id: 19,
    outlet: "정보통신신문",
    date: "2018.08.06",
    title: "제머나이소프트, 중국에 콘텐츠관리시스템 공급",
    summary: "디지털 미디어 관리 플랫폼 전문기업인 제머나이소프트가 중국 최대의 홈쇼핑 서비스 플랫폼 기업인 후이마이온라인 네트워크 과학기술 유한회사(이하 후이마이그룹)에 콘텐츠관리시스템(CMS)을 구축하기로 했다고 밝혔다.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=73682",
    image: "/assets/news/news-0019.png",
  },
  {
    id: 18,
    outlet: "비디오아트",
    date: "2018.08.01",
    title: "제머나이소프트-EBS, 라디오 솔루션 공급 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문 기업 제머나이소프트(대표 강진욱, www.gemiso.co.kr)가 한국교육방송공사(이하 EBS, 대표 장해랑, www.ebs.co.kr)와 라디오 방송 전문 솔루션인 ‘이모션(E.moti.on)’의 독점 공급 계약을 체결했다고 밝혔다.",
    href: "https://www.videoarts.co.kr/customer/news_view.php?bd_id=2352&amp;page=1&amp;s_start=&amp;s_end=&amp;s_cate=01&amp;s_value=&amp;end_no=10",
    image: "/assets/news/news-0018.jpg",
  },
  {
    id: 17,
    outlet: "방송과기술",
    date: "2018.07.31",
    title: "제머나이소프트-EBS, 라디오 솔루션 E.moti.on 공급 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 EBS와 라디오 방송 전문 솔루션인 '이모션(E.moti.on)'의 독점 공급 계약을 체결했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_12b528dfe4534d3889ce1042552436a7.pdf",
    image: "/assets/news/news-0017.jpg",
  },
  {
    id: 16,
    outlet: "비디오플러스",
    date: "2018.07.31",
    title: "제머나이소프트-EBS, 라디오 솔루션 공급 계약 체결",
    summary: "제머나이소프트는 지난 7월 19일 한국교육방송공사(EBS)와 라디오 방송 전문 솔루션인 '이모션(E.moti.on)'의 독점 공급 계약을 체결했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_07197ffd48be46fcb2ce15eef1e2d8e0.pdf",
    image: "/assets/news/news-0016.jpg",
  },
  {
    id: 15,
    outlet: "인터페이스뉴스",
    date: "2018.07.19",
    title: "제머나이소프트-EBS, 라디오 솔루션 공급 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문 기업인 제머나이소프트가 한국교육방송공사(이하 EBS)와 라디오 방송 전문 솔루션인 ‘이모션(E.moti.on)’의 독점 공급 계약을 체결했다고 밝혔다.",
    href: "",
    image: "/assets/news/news-0015.jpg",
  },
  {
    id: 14,
    outlet: "전자신문",
    date: "2018.07.19",
    title: "제머나이소프트, EBS 제휴로 설치와 운영 간편한 라디오 방송 솔루션 ‘이모션’ 공급",
    summary: "디지털 미디어 관리 기업 제머나이소프트(대표 강진욱)가 한국교육방송공사(이하 EBS, 대표 장해랑)와 라디오 방송 전문 솔루션인 ‘이모션(E.moti.on)’의 독점 공급 계약을 체결했다고 19일 밝혔다.",
    href: "https://www.etnews.com/20180719000293",
    image: "/assets/news/news-0014.png",
  },
  {
    id: 13,
    outlet: "연합뉴스",
    date: "2018.07.18",
    title: "EBS, 자체개발 라디오 방송 솔루션 보급 나선다",
    summary: "EBS가 자체개발 라디오 방송 솔루션 보급에 나섰다.",
    href: "https://www.yna.co.kr/view/AKR20180719149400005",
    image: "/assets/news/news-0013.jpg",
  },
  {
    id: 12,
    outlet: "연합뉴스",
    date: "2018.07.18",
    title: "포토뉴스_EBS, 자체개발 라디오 방송 솔루션 보급 나선다",
    summary: "EBS가 19일 경기도 고양시 일산 사옥에서 ㈜제머나이소프트와 자체개발 라디오 방송 솔루션 'E.MOTI.ON' 협력사업 추진을 위한 계약을 체결했다고 전했다",
    href: "https://www.yna.co.kr/view/PYH20180719215400005",
    image: "/assets/news/news-0012.jpg",
  },
  {
    id: 11,
    outlet: "뉴스엔",
    date: "2018.07.18",
    title: "EBS, 제머나이소프트와 자체개발 라디오 방송 솔루션 협력사업 계약체결",
    summary: "EBS가 제머나이소프트와 협력사업 추진을 위한 계약을 체결했다.",
    href: "https://www.newsen.com/news_view.php?uid=201807191813128010",
    image: "/assets/news/news-0011.jpg",
  },
  {
    id: 10,
    outlet: "DATANET",
    date: "2018.07.18",
    title: "제머나이소프트·EBS, 라디오 솔루션 공급 계약 체결",
    summary: "디지털 미디어 관리 플랫폼 전문기업 제머나이소프트(대표 강진욱)는 한국교육방송공사(대표 장해랑, 이하 EBS)와 라디오 방송 전문 솔루션 ‘이모션(E.moti.on)’의 독점 공급 계약을 체결했다고 밝혔다.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=124769",
    image: "/assets/news/news-0010.jpg",
  },
  {
    id: 9,
    outlet: "방송과기술",
    date: "2018.05.30",
    title: "제머나이소프트, KOBA 2018에서 차세대 방송 솔루션 3종 발표",
    summary: "제머나이소프트가 차세대 방송 환경에 대비한 신개념 솔루션 3종을 KOBA 2018에서 전시 및 시연했다.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_2acc7e9a6877418487c78ebaa564aa7b.pdf",
    image: "/assets/news/news-0009.png",
  },
  {
    id: 8,
    outlet: "IT조선",
    date: "2018.05.10",
    title: "[이주의 SW] 유니티 '2018.1'·업비트 '암호화폐 인덱스'·제머나이소프트 솔루션 인기",
    summary: "제머나이소프트 '에어리얼'은 디지털 자산관리 솔루션으로 프로젝트 기반 미디어 관리 기술을 도입했습니다.",
    href: "http://it.chosun.com/site/data/html_dir/2018/05/11/2018051185026.html",
    image: "/assets/news/news-0008.png",
  },
  {
    id: 7,
    outlet: "IT 조선",
    date: "2018.05.09",
    title: "제머나이소프트, KOBA 2018에서 차세대 방송 환경을 위한 솔루션 공개",
    summary: "제머나이소프트는 KOBA 2018에서 차세대 방송 환경에 대비한 신개념 솔루션 3종을 전시·시연한다고 밝혔다.",
    href: "http://it.chosun.com/site/data/html_dir/2018/05/10/2018051085055.html",
    image: "/assets/news/news-0007.png",
  },
  {
    id: 6,
    outlet: "인터페이스뉴스",
    date: "2018.05.08",
    title: "제머나이소프트, ‘UHD MAM·라디오 방송·AR’ 방송 솔루션 발표",
    summary: "제머나이소프트가 차세대 방송 환경에 대비한 신개념 솔루션 3종을 ‘코바(KOBA) 2018’에서 전시 및 시연한다.",
    href: "",
    image: "/assets/news/news-0006.png",
  },
  {
    id: 5,
    outlet: "테크월드",
    date: "2018.05.08",
    title: "제머나이소프트, AR∙UHD MAM 등 차세대 방송 솔루션 발표",
    summary: "제머나이소프트가 차세대 방송 환경을 대비한 솔루션 3종을 KOBA 2018에서 공개한다.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=79916",
    image: "/assets/news/news-0005.png",
  },
  {
    id: 4,
    outlet: "IT World",
    date: "2018.05.08",
    title: "제머나이소프트, 차세대 방송 솔루션 3종 발표",
    summary: "제머나이소프트가 차세대 방송 환경에 대비한 신개념 솔루션 3종을 KOBA 2018에서 전시 및 시연한다고 밝혔다.",
    href: "https://www.itworld.co.kr/news/109238",
    image: "/assets/news/news-0004.png",
  },
  {
    id: 3,
    outlet: "CIO Korea",
    date: "2018.05.08",
    title: "제머나이소프트, 차세대 방송 솔루션 3종 발표",
    summary: "제머나이소프트가 차세대 방송 환경에 대비한 신개념 솔루션 3종을 KOBA 2018에서 전시 및 시연한다고 밝혔다.",
    href: "https://www.ciokorea.com/news/38184",
    image: "/assets/news/news-0003.png",
  },
  {
    id: 2,
    outlet: "AVING",
    date: "2018.05.07",
    title: "[미리보는 KOBA 2018] 제머나이소프트, 차세대 방송 솔루션 3종 발표",
    summary: "제머나이소프트는 '국제방송·음향·조명기기전시회(KOBA 2018)'에 참가해 차세대 방송 환경에 대비한 신개념 솔루션 3종을 선보인다.",
    href: "http://kr.aving.net/news/view.php?articleId=1385973&amp;Branch_ID=kr&amp;rssid=naver&amp;mn_name=news",
    image: "/assets/news/news-0002.png",
  },
  {
    id: 1,
    outlet: "",
    date: "2018.04.24",
    title: "CJ 오쇼핑, 제머나이소프트 AR 솔루션 적용",
    summary: "제머나이소프트의 AR(증강현실) 3D 그래픽 솔루션인 '네메시스(Nemesis)'가 CJ오쇼핑의 AR 스튜디오를 통해 실제 방송에 적용됐다.",
    href: "",
    image: "/assets/news/news-0001.png",
  },
];

/** id로 기사 한 건을 찾는다. */
export function getArticle(id: string | number): NewsArticle | undefined {
  const n = typeof id === "string" ? Number(id) : id;
  return NEWS_ARTICLES.find((a) => a.id === n);
}

/** 현재 기사를 제외한 관련 소식(최신순)을 count개 반환한다. */
export function relatedArticles(id: number, count = 3): NewsArticle[] {
  return NEWS_ARTICLES.filter((a) => a.id !== id).slice(0, count);
}
