/**
 * 뉴스 데이터 — 뉴스룸 목록(/news)과 상세(/news/[id]) 페이지의 단일 소스.
 *
 * gemiso.co.kr/news 의 언론보도(보도자료) 클리핑 139건을 추출해 정적 데이터로
 * 구성한 것. 최신순으로 정렬돼 있으며, 첫 항목이 주요 소식(featured)이 된다.
 * 새 소식은 이 배열 맨 앞에 항목을 추가하면 목록·상세가 자동으로 갱신된다.
 *
 * 이미지는 public/assets/news 에 저장돼 있고, image 값은 basePath 없이
 * 기록한다(컴포넌트에서 asset()으로 경로를 보정).
 */

export type NewsArticle = {
  /** URL 식별자(숫자) */
  id: number;
  /** 보도 매체명 — 없으면 빈 문자열 */
  outlet: string;
  /** 발행일 (YYYY.MM.DD) */
  date: string;
  /** 기사 제목 */
  title: string;
  /** 요약 본문 */
  summary: string;
  /** 원문 기사 URL — 없으면 빈 문자열 */
  href: string;
  /** 대표 이미지 경로(/assets/news/...) — 없으면 null */
  image: string | null;
};

/** 최신순으로 정렬된 보도 클리핑 목록. */
export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 140,
    outlet: "Newsis",
    date: "2026.04.30",
    title: "GEMISO to Lead Government Broadcast Media R&D Project 'MyMedia Platform Core Technology Development'",
    summary:
      "GEMISO will lead the 'core technology development for a MyMedia platform for personalized media services,' one of the digital media innovation technology projects selected by the Broadcasting, Media and Communications Commission and the Institute of Information & Communications Technology Planning & Evaluation (IITP). Together with KETI and ETRI, the company will combine persona AI models with metadata technology to develop personalization technology that reconstructs content and automatically links scenes based on each user's viewing patterns and interests. The government plans to invest some 72.7 billion won in broadcast media R&D over five years through 2030.",
    href: "https://www.newsis.com/view/NISX20260430_0003613403",
    image: "/assets/news/news-0140.jpg",
  },
  {
    id: 141,
    outlet: "",
    date: "2026.04.18",
    title: "GEMISO to Exhibit at 'NAB Show 2026' — Showcasing AI Training Data Built from Broadcast Content",
    summary:
      "GEMISO will exhibit at 'NAB Show 2026' (Central Hall, Futures Park C4449-G), the world's largest broadcast and media trade show, held in Las Vegas. Under the slogan 'Better Data. Better AI.', the company will present an end-to-end service for building high-quality AI training datasets from broadcast video content — spanning data strategy consulting, three-stage CoT labeling and quality assurance, and development of text-to-image and text-to-video sample models.",
    href: "https://www.gemiso.com/ai-dataset",
    image: null,
  },
  {
    id: 139,
    outlet: "IT Chosun",
    date: "2026.01.30",
    title: "GEMISO Joins KBS Multi-Platform Integrated Master Control Deployment Project",
    summary: "GEMISO will take part in KBS's multi-platform integrated master control room (MCR) deployment project, supplying its integrated content management (MAM) and AI-based video quality control solutions.",
    href: "https://it.chosun.com/news/articleView.html?idxno=2023092156052",
    image: "/assets/news/news-0139.png",
  },
  {
    id: 138,
    outlet: "Digital Times",
    date: "2026.01.30",
    title: "GEMISO Selected as Supply Partner for KBS Multi-Platform Integrated Master Control Project",
    summary: "GEMISO has been selected as the supply partner for the integrated content management (MAM) system and AI-based QC solution in KBS's multi-platform integrated master control room (MCR) deployment project.",
    href: "https://www.dt.co.kr/article/12043867?ref=naver",
    image: "/assets/news/news-0138.png",
  },
  {
    id: 137,
    outlet: "The Electronic Times",
    date: "2026.01.30",
    title: "GEMISO Named Supply Partner for KBS Multi-Platform Integrated Master Control Project",
    summary: "GEMISO has been selected to supply its integrated content management (MAM) and AI-based video quality control (QC) solutions for KBS's multi-platform integrated master control room (MCR) deployment project.",
    href: "https://www.etnews.com/20260130000251",
    image: "/assets/news/news-0137.png",
  },
  {
    id: 136,
    outlet: "Maeil Shinmun",
    date: "2026.01.13",
    title: "GEMISO Supplies Automated Playout Solution 'TALOS' to Pay-TV Operator's Local Channels",
    summary: "GEMISO supplies its automated playout solution 'TALOS' to a pay-TV operator's local channels.",
    href: "https://www.imaeil.com/page/view/2026011413551706783",
    image: "/assets/news/news-0136.png",
  },
  {
    id: 135,
    outlet: "The Electronic Times",
    date: "2026.01.13",
    title: "GEMISO Supplies Automated Playout Solution 'TALOS' for Major Pay-TV Operator's Local-Channel DR System",
    summary: "GEMISO supplies its automated playout solution 'TALOS' for the disaster recovery (DR) system of a major pay-TV operator's local channels.",
    href: "https://www.etnews.com/20260113000338",
    image: "/assets/news/news-0135.png",
  },
  {
    id: 134,
    outlet: "Digital Daily",
    date: "2026.01.13",
    title: "GEMISO Supplies DR Playout System for Pay-TV Local Channels",
    summary: "GEMISO supplies a DR playout system for a pay-TV operator's local channels.",
    href: "https://www.ddaily.co.kr/page/view/2026011314485519847",
    image: "/assets/news/news-0134.png",
  },
  {
    id: 133,
    outlet: "",
    date: "2025.03.17",
    title: "4by4 Signs MOU with GEMISO to Co-Develop AI Solution Plug-in",
    summary: "4by4's picture-quality enhancement AI 'PIXELL' will be offered as a plug-in optimized for GEMISO's media asset management system.",
    href: "https://search.naver.com/search.naver?sm=tab_hty.top&amp;where=news&amp;ssc=tab.news.all&amp;query=%EC%A0%9C%EB%A8%B8%EB%82%98%EC%9D%B4%EC%86%8C%ED%94%84%ED%8A%B8+AI+%EC%86%94%EB%A3%A8%EC%85%98+%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8&amp;oquery=%EC%A0%9C%EB%A8%B8%EB%82%98%EC%9D%B4%EC%86%8C%ED%94%84%ED%8A%B8+ai+%EC%86%94%EB%A3%A8%EC%85%98+%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8&amp;tqi=i9X9PspzL8VssESLEvNssssssXw-511880&amp;nso=so%3Ar%2Cp%3Aall%2Ca%3Aall&amp;mynews=0&amp;office_section_code=0&amp;office_type=0&amp;pd=0&amp;photo=0&amp;sort=0",
    image: "/assets/news/news-0133.png",
  },
  {
    id: 132,
    outlet: "",
    date: "2025.02.25",
    title: "GEMISO to Exhibit at NAB Show 2025",
    summary: "GEMISO will showcase its latest media workflow technology at NAB Show 2025.\nCome experience the solutions transforming content management firsthand!",
    href: "https://nab25.mapyourshow.com/8_0/exhibitor/exhibitor-details.cfm?exhid=8800723",
    image: "/assets/news/news-0132.png",
  },
  {
    id: 131,
    outlet: "",
    date: "2025.02.20",
    title: "GEMISO Officially Sponsors the 38th Korea Video Journalist Awards Ceremony",
    summary: "Digital media management company GEMISO took part as an official sponsor of the 38th Korea Video Journalist Awards ceremony, Korea's most prestigious awards in broadcast news video.",
    href: "https://7bafc12f-77bb-4c18-aa3b-3df2789078ed.usrfiles.com/ugd/7bafc1_f10a7c7dd80249218e1e327e64261891.pdf",
    image: "/assets/news/news-0131.jpg",
  },
  {
    id: 130,
    outlet: "",
    date: "2024.10.28",
    title: "GEMISO Announces Official Sponsorship of 'Video Dev Days 2024'",
    summary: "GEMISO, a company specializing in digital media management platforms, announced it will take part as an official sponsor of 'Video Dev Days 2024', hosted by VideoLAN, the organization behind the open-source video library and video player.",
    href: "https://www.etnews.com/20241025000295",
    image: "/assets/news/news-0130.png",
  },
  {
    id: 129,
    outlet: "",
    date: "2024.10.28",
    title: "GEMISO Joins 'Video Dev Days 2024' as Official Sponsor",
    summary: "Digital media management company GEMISO will serve as an official sponsor of 'Video Dev Days 2024', hosted by VideoLAN at Kwangwoon University on November 2.",
    href: "https://www.wowtv.co.kr/NewsCenter/News/Read?articleId=A202410250349&amp;t=NN",
    image: "/assets/news/news-0129.png",
  },
  {
    id: 128,
    outlet: "",
    date: "2024.10.25",
    title: "GEMISO Officially Sponsors 'Video Dev Days 2024', Contributing to the Open-Source Multimedia Ecosystem",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced it will take part as an official sponsor of 'Video Dev Days 2024', hosted by VideoLAN.",
    href: "https://www.videosound.co.kr/situation_news/?q=YToxOntzOjEyOiJrZXl3b3JkX3R5cGUiO3M6MzoiYWxsIjt9&amp;bmode=view&amp;idx=123431066&amp;t=board",
    image: "/assets/news/news-0128.png",
  },
  {
    id: 127,
    outlet: "",
    date: "2024.04.04",
    title: "HUFS Holds Video Art Archive Seminar on 'Nam June Paik's Video Study'",
    summary: "The Research Institute for Information and Archival Science at Hankuk University of Foreign Studies held an online seminar on the 7th on the video archive of Korean video artist Nam June Paik, under the theme 'Nam June Paik's Video Study.'",
    href: "https://m.dhnews.co.kr/news/view/1065579738924891",
    image: "/assets/news/news-0127.png",
  },
  {
    id: 126,
    outlet: "",
    date: "2023.12.08",
    title: "GEMISO Signs Product and Technology Transfer Agreement with ADSoft",
    summary: "The deal integrates GEMISO's video technology with ADSoft's radio solution technology.",
    href: "http://www.itdaily.kr/news/articleView.html?idxno=218716",
    image: "/assets/news/news-0126.png",
  },
  {
    id: 125,
    outlet: "",
    date: "2023.12.08",
    title: "GEMISO Signs Product and Technology Transfer and Integration Agreement with ADSoft",
    summary: "GEMISO signed a product and technology transfer and integration agreement with ADSoft on the 4th.",
    href: "https://www.etnews.com/20231208000152",
    image: "/assets/news/news-0125.png",
  },
  {
    id: 124,
    outlet: "",
    date: "2023.12.08",
    title: "GEMISO and ADSoft Sign Product and Technology Transfer Agreement for Radio and Audio Solutions",
    summary: "GEMISO, a company specializing in digital media management platforms, and ADSoft, a radio broadcasting systems company, signed a product and technology transfer and integration agreement on the 4th.",
    href: "https://www.segye.com/newsView/20231208511608?OutUrl=naver",
    image: "/assets/news/news-0124.png",
  },
  {
    id: 123,
    outlet: "",
    date: "2023.11.24",
    title: "Arirang TV Advances Bilingual AI Anchor, Leading Global Innovation",
    summary: "This year, Arirang TV successfully completed its bilingual AI anchor project in collaboration with AI specialists DeepBrain AI, Xinapse, and GEMISO. The project achieved a high level of AI human and bilingual processing technology, and Arirang TV is expected to set a new standard for media innovation with a regularly scheduled news program powered by the technology.",
    href: "https://n.news.naver.com/mnews/article/015/0004917945?sid=105",
    image: "/assets/news/news-0123.jpg",
  },
  {
    id: 122,
    outlet: "",
    date: "2023.11.24",
    title: "Arirang TV Debuts Korea's First Live AI Anchor Newscast",
    summary: "This year, Arirang TV completed its bilingual AI anchor project in collaboration with AI specialists DeepBrain AI, Xinapse, and GEMISO. Arirang TV said it has \"implemented AI human and bilingual processing technology at a high level\" and expressed confidence that the news program built on it \"will set a new standard for media innovation.\"",
    href: "https://www.kukinews.com/newsView/kuk202311240081",
    image: "/assets/news/news-0122.jpg",
  },
  {
    id: 121,
    outlet: "",
    date: "2023.11.23",
    title: "Arirang TV Launches News Program Hosted by Bilingual AI Anchors",
    summary: "Arirang TV announced on the 23rd that it is launching a news program presented by AI anchors.",
    href: "https://www.yna.co.kr/view/AKR20231123139000005?input=1195m",
    image: "/assets/news/news-0121.jpg",
  },
  {
    id: 120,
    outlet: "Information & Communication Newspaper",
    date: "2021.12.16",
    title: "GEMISO Consortium Demonstrates Mixed Reality Service",
    summary: "Exhibited at 'KMF & KME 2021'\nResults of the convergence service competitiveness project\nEasy AR video production without expensive equipment",
    href: "https://www.koit.co.kr/news/articleView.html?idxno=91950",
    image: "/assets/news/news-0120.jpg",
  },
  {
    id: 119,
    outlet: "Newswire",
    date: "2021.12.15",
    title: "GEMISO Consortium Exhibits Results of ICT Convergence Service Competitiveness Project",
    summary: "GEMISO, Kwangwoon University's Spatial Computing Lab, the Korea VR/AR Industry Association, and Party in Space (the consortium) presented the results of the 'AR Cloud-based open Anchor development for universal mixed reality services' project...",
    href: "https://www.newswire.co.kr/newsRead.php?no=936572",
    image: "/assets/news/news-0119.jpg",
  },
  {
    id: 118,
    outlet: "Video Plus",
    date: "2020.07.01",
    title: "GEMISO Scores a Triple Crown of Grade 1 GS Certifications",
    summary: "Three of GEMISO's in-house media management solutions have recently earned Grade 1 GS (Good Software) certification in succession.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106621%26pagecnt%3D0%26letter_no%3D13%26offset%3D0%26search%3Dname%26searchstring%3D%C1%A6%B8%D3%B3%AA%C0%CC%BC%D2%C7%C1%C6%AE%26present_num%3D13&amp;boardIndex=1&amp;serin=1",
    image: "/assets/news/news-0118.jpg",
  },
  {
    id: 117,
    outlet: "Digital Economy News",
    date: "2020.06.04",
    title: "Three GEMISO Products Earn Grade 1 GS Certification",
    summary: "Three of GEMISO's specialized media management solutions have recently earned Grade 1 GS (Good Software) certification in succession.",
    href: "http://www.denews.co.kr/news/articleView.html?idxno=13660",
    image: "/assets/news/news-0117.png",
  },
  {
    id: 116,
    outlet: "Digital Daily",
    date: "2020.06.03",
    title: "GEMISO's Three Media Management Solutions Earn GS Grade 1",
    summary: "GEMISO announced on the 3rd that three of its in-house media management solutions have earned Grade 1 Good Software (GS) certification.",
    href: "https://www.ddaily.co.kr/news/article/?no=196447",
    image: "/assets/news/news-0116.png",
  },
  {
    id: 115,
    outlet: "Video Arts",
    date: "2020.06.03",
    title: "GEMISO Successfully Deploys HD Integrated System for CPBC",
    summary: "GEMISO (CEO Kang Jin-wook, www.gemiso.co.kr) announced it has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation (CEO Cho Jung-rae, www.cpbc.co.kr; CPBC) as part of the broadcaster's transition to HD (High Definition) TV production.",
    href: "https://www.videoarts.co.kr/customer/news_view.php?bd_id=2704&amp;page=1&amp;s_start=&amp;s_end=&amp;s_cate=01&amp;s_value=&amp;end_no=10",
    image: "/assets/news/news-0115.jpg",
  },
  {
    id: 114,
    outlet: "Information & Communication Newspaper",
    date: "2020.06.03",
    title: "GEMISO's Homegrown Media Management Solutions Stand Out",
    summary: "Three media management solutions developed in-house by GEMISO have recently earned Grade 1 GS (Good Software) certification in succession.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=78951",
    image: "/assets/news/news-0114.jpg",
  },
  {
    id: 113,
    outlet: "Digital Today",
    date: "2020.06.02",
    title: "GEMISO Earns GS Certification for Image Management Solution as Well",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook, www.gemiso.co.kr) announced on the 3rd that its in-house image management solution 'Ariel Image Archive' has received Grade 1 Good Software (GS) certification.",
    href: "http://www.digitaltoday.co.kr/news/articleView.html?idxno=236772",
    image: "/assets/news/news-0113.jpg",
  },
  {
    id: 112,
    outlet: "DATANET",
    date: "2020.06.02",
    title: "GEMISO's Three Media Management Solutions Earn 'Grade 1 GS Certification'",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced on the 3rd that three of its in-house media management solutions have recently earned Grade 1 GS (Good Software) certification in succession.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=146662",
    image: "/assets/news/news-0112.png",
  },
  {
    id: 111,
    outlet: "The Electronic Times",
    date: "2020.06.02",
    title: "GEMISO's Three Media Management Solutions Earn Grade 1 GS Certification in Succession",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced that three of its in-house media management solutions have recently earned Grade 1 GS (Good Software) certification in succession.",
    href: "https://www.etnews.com/20200603000242",
    image: "/assets/news/news-0111.jpg",
  },
  {
    id: 110,
    outlet: "IT Biz",
    date: "2020.06.02",
    title: "GEMISO's Three Specialized Media Management Solutions Earn Grade 1 GS Certification",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 3rd that three of its in-house media management solutions have recently earned Grade 1 GS (Good Software) certification in succession.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=41060",
    image: "/assets/news/news-0110.jpg",
  },
  {
    id: 109,
    outlet: "Broadcasting & Technology",
    date: "2020.05.30",
    title: "GEMISO Successfully Builds HD Integrated System for CPBC",
    summary: "GEMISO has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation (CPBC) as part of its transition to HD TV production.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_0907e3abe4b641729f4d69d06ca12eec.pdf",
    image: "/assets/news/news-0109.jpg",
  },
  {
    id: 108,
    outlet: "Video Plus",
    date: "2020.05.30",
    title: "GEMISO Delivers One-Stop Workflow Integration from Broadcast Production to Editing and Delivery",
    summary: "GEMISO announced it has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation as part of the broadcaster's transition to HD TV production.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_c74525eb86664619982068a1cb367c24.pdf",
    image: "/assets/news/news-0108.jpg",
  },
  {
    id: 107,
    outlet: "DATANET",
    date: "2020.05.06",
    title: "GEMISO Deploys HD Integrated System for CPBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it has successfully deployed an integrated system for the Catholic Peace Broadcasting Corporation (CEO Cho Jung-rae) as part of its transition to HD (High Definition) TV production.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=145576",
    image: "/assets/news/news-0107.jpg",
  },
  {
    id: 106,
    outlet: "IT Biz",
    date: "2020.05.06",
    title: "GEMISO Completes HD Integrated System for CPBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation (CEO Cho Jung-rae) as part of its transition to HD (High Definition) TV production.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=40341",
    image: "/assets/news/news-0106.jpg",
  },
  {
    id: 105,
    outlet: "IT World",
    date: "2020.05.06",
    title: "GEMISO Completes HD Integrated System for CPBC",
    summary: "GEMISO (www.gemiso.co.kr) announced it has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation (www.cpbc.co.kr) as part of its transition to HD (High Definition) TV production.",
    href: "https://www.itworld.co.kr/news/151952",
    image: "/assets/news/news-0105.jpg",
  },
  {
    id: 104,
    outlet: "Bloter",
    date: "2020.05.06",
    title: "GEMISO Wraps Up HD Integrated System for CPBC",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced on May 7 that it has completed the integrated system deployment project for the Catholic Peace Broadcasting Corporation's (CEO Cho Jung-rae; CPBC) transition to HD (High Definition) TV production.",
    href: "https://www.bloter.net/newsView/blt202005070012",
    image: "/assets/news/news-0104.jpg",
  },
  {
    id: 103,
    outlet: "Information & Communication Newspaper",
    date: "2020.05.06",
    title: "GEMISO Builds HD Integrated System for CPBC",
    summary: "GEMISO announced on the 7th that it has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation's transition to HD TV production.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=78774",
    image: "/assets/news/news-0103.jpg",
  },
  {
    id: 102,
    outlet: "The Electronic Times",
    date: "2020.05.05",
    title: "GEMISO Deploys HD Integrated System at CPBC",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced it has successfully completed an integrated system for the Catholic Peace Broadcasting Corporation's (CEO Cho Jung-rae) transition to HD (High Definition) TV production.",
    href: "https://www.etnews.com/20200507000212",
    image: "/assets/news/news-0102.jpg",
  },
  {
    id: 101,
    outlet: "Broadcasting & Technology",
    date: "2020.04.01",
    title: "GEMISO's GPU Transcoder Earns Grade 1 GS Certification",
    summary: "The Ariel GPU Transcoder, a transcoder product from digital media management platform company GEMISO, recently earned Grade 1 GS (Good Software) certification.",
    href: "http://tech.kobeta.com/%ec%a0%9c%eb%a8%b8%eb%82%98%ec%9d%b4%ec%86%8c%ed%94%84%ed%8a%b8-gpu-%ed%8a%b8%eb%9e%9c%ec%8a%a4%ec%bd%94%eb%8d%94-gs%ec%9d%b8%ec%a6%9d-1%eb%93%b1%ea%b8%89-%ed%9a%8d%eb%93%9d/",
    image: "/assets/news/news-0101.png",
  },
  {
    id: 100,
    outlet: "Video Plus",
    date: "2020.03.14",
    title: "GEMISO's GPU Transcoder Wins Grade 1 GS Certification",
    summary: "GEMISO's transcoder product, the Ariel GPU Transcoder, recently earned Grade 1 GS (Good Software) certification.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106523%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0100.png",
  },
  {
    id: 99,
    outlet: "Video Plus",
    date: "2020.01.07",
    title: "GEMISO Receives Minister of Science and ICT Commendation for Outstanding Global Performance",
    summary: "GEMISO was named an outstanding global performer at the 2019 ICT and Broadcasting Program Performance Conference and received the Minister of Science and ICT Award.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106396%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0099.jpg",
  },
  {
    id: 98,
    outlet: "Broadcasting & Technology",
    date: "2020.01.05",
    title: "GEMISO Wins Minister of Science and ICT Commendation for Outstanding Global Performance",
    summary: "GEMISO, a company specializing in digital media management platforms, was named an outstanding global performer at the 2019 ICT and Broadcasting Program Performance Conference and received the Minister of Science and ICT Award.",
    href: "http://tech.kobeta.com/%ec%a0%9c%eb%a8%b8%eb%82%98%ec%9d%b4%ec%86%8c%ed%94%84%ed%8a%b8-%ea%b8%80%eb%a1%9c%eb%b2%8c-%ec%9a%b0%ec%88%98-%ec%84%b1%ea%b3%bc-%ea%b3%bc%ea%b8%b0%ec%a0%95%ed%86%b5%eb%b6%80%ec%9e%a5/",
    image: "/assets/news/news-0098.jpg",
  },
  {
    id: 97,
    outlet: "The Electronic Times",
    date: "2019.12.10",
    title: "[ICT Industry Catalysts: ICT and Broadcasting Programs] (1) SMEs and Venture Firms Take Wing for Global Growth",
    summary: "GEMISO took part in the 'Broadcasting Environment Improvement Support for Developing Countries' program, which aims to improve broadcast environments in developing countries and expand the international footprint of Korea's broadcasting industry.",
    href: "https://www.etnews.com/20191211000072",
    image: "/assets/news/news-0097.jpg",
  },
  {
    id: 96,
    outlet: "Inews24",
    date: "2019.12.10",
    title: "KCA Holds 2019 ICT and Broadcasting Program Performance Conference",
    summary: "The Korea Communications Agency (KCA) held this year's ICT and Broadcasting Program Performance Conference.",
    href: "https://www.inews24.com/view/1228502",
    image: "/assets/news/news-0096.jpg",
  },
  {
    id: 95,
    outlet: "DATANET",
    date: "2019.09.08",
    title: "GEMISO CEO Kang Jin-wook: 'Expanding into New Businesses on Specialized Media Technology'",
    summary: "We visited GEMISO, a company focused on extending its reach beyond Korea into overseas markets, to hear more. The following is a Q&A with GEMISO CEO Kang Jin-wook.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=137201",
    image: "/assets/news/news-0095.jpg",
  },
  {
    id: 94,
    outlet: "DATANET",
    date: "2019.09.08",
    title: "GEMISO: 'Leaping Forward as a Global Digital Media Solution Company'",
    summary: "Expanding video-specialized solutions on solid technology... also pursuing a professional distribution service model",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=137198",
    image: "/assets/news/news-0094.jpg",
  },
  {
    id: 93,
    outlet: "Video Plus",
    date: "2019.09.03",
    title: "GEMISO CEO Kang Jin-wook: 'Going Beyond Korea to Global Markets'",
    summary: "Completing a single video requires not only shooting but also organically connected systems for editing, playout, and more. GEMISO is a Korean company specializing in managing all of this efficiently.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106155%26pagecnt%3D0%26letter_no%3D25%26offset%3D0%26search%3D%26searchstring%3D%26present_num%3D24&amp;boardIndex=28&amp;pc=",
    image: "/assets/news/news-0093.jpg",
  },
  {
    id: 92,
    outlet: "Video Plus",
    date: "2019.08.08",
    title: "GEMISO Completes News Production System for Gwangju MBC",
    summary: "GEMISO announced it has successfully completed a Network Production System (NPS) for Gwangju Munhwa Broadcasting Corporation (Gwangju MBC).",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D106108%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0092.png",
  },
  {
    id: 91,
    outlet: "Broadcast Technology Journal",
    date: "2019.07.23",
    title: "GEMISO Wraps Up News Production System for Gwangju MBC",
    summary: "Following MBC, GEMISO has deployed its Network Production System (NPS) at Gwangju MBC as well.",
    href: "http://journal.kobeta.com/%ec%a0%9c%eb%a8%b8%eb%82%98%ec%9d%b4%ec%86%8c%ed%94%84%ed%8a%b8-%ea%b4%91%ec%a3%bcmbc-%eb%b3%b4%eb%8f%84-%ec%a0%9c%ec%9e%91-%ec%8b%9c%ec%8a%a4%ed%85%9c-%ea%b5%ac%ec%b6%95-%ec%99%84%eb%a3%8c/",
    image: "/assets/news/news-0091.png",
  },
  {
    id: 90,
    outlet: "The Electronic Times",
    date: "2019.07.22",
    title: "GEMISO Completes News Production System Deployment for Gwangju MBC",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced on the 23rd that it has completed a Network Production System (NPS) for Gwangju Munhwa Broadcasting Corporation (CEO Song Il-jun; Gwangju MBC).",
    href: "https://www.etnews.com/20190723000322",
    image: "/assets/news/news-0090.png",
  },
  {
    id: 89,
    outlet: "IT Chosun",
    date: "2019.07.22",
    title: "GEMISO Deploys Network-Based News Production System at Gwangju MBC",
    summary: "Digital media management platform company GEMISO announced on the 23rd that it has completed deployment of its Network Production System (NPS) at Gwangju Munhwa Broadcasting Corporation (Gwangju MBC).",
    href: "http://it.chosun.com/site/data/html_dir/2019/07/23/2019072301167.html",
    image: "/assets/news/news-0089.png",
  },
  {
    id: 88,
    outlet: "DATANET",
    date: "2019.07.22",
    title: "GEMISO Finishes News Production System for Gwangju MBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 23rd that it has successfully completed a Network Production System (NPS) for Gwangju Munhwa Broadcasting Corporation (CEO Song Il-jun; Gwangju MBC).",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=135846",
    image: "/assets/news/news-0088.png",
  },
  {
    id: 87,
    outlet: "IT Biz",
    date: "2019.07.22",
    title: "GEMISO Completes News Production System for Gwangju MBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 23rd that it has completed a Network Production System (NPS) for Gwangju Munhwa Broadcasting Corporation (CEO Song Il-jun).",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=32180",
    image: "/assets/news/news-0087.png",
  },
  {
    id: 86,
    outlet: "Digital Daily",
    date: "2019.07.22",
    title: "GEMISO Builds News Production System for Gwangju MBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 23rd that it has completed a network-based production system (NPS) for Gwangju MBC.",
    href: "https://www.ddaily.co.kr/news/article/?no=183840",
    image: "/assets/news/news-0086.png",
  },
  {
    id: 85,
    outlet: "Semiconductor Network",
    date: "2019.06.18",
    title: "Different, Scalable and Fast UHD Transcoding 10min 'Proxima'",
    summary: "Different, Scalable and Fast UHD Transcoding 10min “Proxima”",
    href: "https://www.seminet.co.kr/channel_micro.html?menu=video_sub&amp;com_no=817&amp;video_id=9885&amp;cate_no=33&amp;cate_name=Exhibition",
    image: "/assets/news/news-0085.jpg",
  },
  {
    id: 84,
    outlet: "Video Arts",
    date: "2019.05.30",
    title: "KOBA 2019",
    summary: "Special Issue/KOBA 2019",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_1cd9b9469b6d493e8c27fbec990260f1.pdf",
    image: "/assets/news/news-0084.jpg",
  },
  {
    id: 83,
    outlet: "Video Plus",
    date: "2019.05.30",
    title: "Media Creates Choices — KOBA 2019",
    summary: "Major exhibitors at KOBA 2019",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_60d22cf3dd0e4040bf140e1375784a04.pdf",
    image: "/assets/news/news-0083.jpg",
  },
  {
    id: 82,
    outlet: "Broadcasting & Technology",
    date: "2019.05.30",
    title: "GEMISO Completes 'NPS·M' News Production System for MBC",
    summary: "GEMISO, a company specializing in digital media management platforms, has successfully completed the 'NPS·M' project, a newsroom NPS that upgrades MBC's news production workflow.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_85011b93c7e4414e9edc9d3e8b652f30.pdf",
    image: "/assets/news/news-0082.png",
  },
  {
    id: 81,
    outlet: "Nextdaily",
    date: "2019.05.30",
    title: "Exploding Media Data — What Is the Optimal, Profitable Way to Manage It?",
    summary: "GEMISO's media asset management (MAM) solution, which manages data across its entire lifecycle from creation to disposal, offers an optimal answer for companies struggling with media asset management.",
    href: "http://www.nextdaily.co.kr/news/articleView.html?idxno=76286",
    image: "/assets/news/news-0081.png",
  },
  {
    id: 80,
    outlet: "IT Daily",
    date: "2019.05.19",
    title: "GEMISO Integrates Cloud Object Storage with Its MAM Solution",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 20th that it now offers enhanced functionality by integrating cloud object storage with its media asset management (MAM) solution.",
    href: "http://www.itdaily.kr/news/articleView.html?idxno=94813",
    image: "/assets/news/news-0080.png",
  },
  {
    id: 79,
    outlet: "Information & Communication Newspaper",
    date: "2019.05.19",
    title: "[KOBA 2019] A Flood of Korean Broadcast Equipment Armed with Technology",
    summary: "[GEMISO] Unveils MAM system with greatly enhanced security",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=75584",
    image: "/assets/news/news-0079.png",
  },
  {
    id: 78,
    outlet: "The Electronic Times",
    date: "2019.05.19",
    title: "GEMISO Unveils 'Cloud Media Management Solution' with Object Storage Integration",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced it will showcase a cloud-based object storage solution integrated with its media asset management (MAM) solution at the 29th Korea International Broadcast, Audio & Lighting Equipment Show (KOBA 2019), running for four days from May 22 to 25.",
    href: "https://www.etnews.com/20190520000139",
    image: "/assets/news/news-0078.png",
  },
  {
    id: 77,
    outlet: "TechWorld",
    date: "2019.05.19",
    title: "GEMISO Unveils MAM Solution Integrated with Object Storage",
    summary: "Digital media management platform company GEMISO (GEMISO) announced its media asset management (MAM) solution integrated with object storage.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=90413",
    image: "/assets/news/news-0077.png",
  },
  {
    id: 76,
    outlet: "DATANET",
    date: "2019.05.19",
    title: "GEMISO Showcases Media Management Solution with Object Storage Integration",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced on the 20th that it is launching a system that integrates object storage with its media asset management (MAM) solution.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=134041",
    image: "/assets/news/news-0076.png",
  },
  {
    id: 75,
    outlet: "Video Plus",
    date: "2019.03.21",
    title: "GEMISO Wraps Up 'NPS·M' News Production System for MBC",
    summary: "GEMISO announced it has successfully completed the NPS·M project, a newsroom Network Production System (NPS) that upgrades MBC's news production workflow.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105687%26pagecnt%3D0%26letter_no%3D606%26offset%3D0%26search%3D%26searchstring%3D%26present_num%3D602&amp;boardIndex=1&amp;pc=",
    image: "/assets/news/news-0075.png",
  },
  {
    id: 74,
    outlet: "Information & Communication Newspaper",
    date: "2019.03.19",
    title: "GEMISO Completes News Production System for MBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced it has successfully completed the 'NPS·M' project, a network-based news production system (NPS) that upgrades MBC's news production workflow.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74951",
    image: "/assets/news/news-0074.png",
  },
  {
    id: 73,
    outlet: "The Electronic Times",
    date: "2019.03.18",
    title: "GEMISO Completes 'NPS·M' Production and News System for MBC",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced it has successfully completed the 'NPS·M' project, a newsroom NPS (Network Production System) that upgrades the news production workflow at MBC (CEO Choi Seung-ho).",
    href: "https://www.etnews.com/20190319000265",
    image: "/assets/news/news-0073.png",
  },
  {
    id: 72,
    outlet: "IT Biz",
    date: "2019.03.18",
    title: "GEMISO Completes 'NPSㆍM' News NPS for MBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 19th that it has successfully completed the 'NPSㆍM' project, a newsroom NPS (Network Production System) that upgrades the news production workflow at MBC (CEO Choi Seung-ho).",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=29015",
    image: "/assets/news/news-0072.png",
  },
  {
    id: 71,
    outlet: "Digital Daily",
    date: "2019.03.18",
    title: "GEMISO Upgrades MBC's News Production System",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 19th that it has successfully completed the 'NPS·M' project, a newsroom NPS (Network Production System) that upgrades MBC's news production process.",
    href: "https://www.ddaily.co.kr/news/article/?no=179043",
    image: "/assets/news/news-0071.png",
  },
  {
    id: 70,
    outlet: "DATANET",
    date: "2019.03.18",
    title: "GEMISO Completes News NPS for MBC",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 19th that it has successfully completed the 'NPS·M' project, a newsroom NPS (Network Production System) for MBC (CEO Choi Seung-ho).",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=132060",
    image: "/assets/news/news-0070.png",
  },
  {
    id: 69,
    outlet: "Video Arts",
    date: "2019.02.27",
    title: "GEMISO Deploys 'E.moti.on' at Radio Pakistan",
    summary: "GEMISO (CEO Kang Jin-wook, www.gemiso.co.kr), a company specializing in digital media management platforms, announced it has successfully deployed its radio broadcasting solution 'E.moti.on' at Radio Pakistan Multan (www.radio.gov.pk).",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_c262041a58c248cfa6152bb9ddf2b1cb.pdf",
    image: "/assets/news/news-0069.jpg",
  },
  {
    id: 68,
    outlet: "Video Plus",
    date: "2019.02.27",
    title: "GEMISO Completes 'E.moti.on' Deployment at Radio Pakistan",
    summary: "GEMISO announced it has deployed its radio broadcasting solution 'E.moti.on' at Radio Pakistan Multan (www.radio.gov.pk).",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105642%26pagecnt%3D0%26letter_no%3D590%26offset%3D0%26search%3D%26searchstring%3D%26present_num%3D585&amp;boardIndex=1&amp;pc=",
    image: "/assets/news/news-0068.jpg",
  },
  {
    id: 67,
    outlet: "Information & Communication Newspaper",
    date: "2019.02.26",
    title: "GEMISO Supplies Radio Broadcasting Solution to Pakistan",
    summary: "GEMISO (CEO Kang Jin-wook) announced it has successfully deployed its radio broadcasting solution 'E.moti.on' at Pakistan's state radio broadcaster.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74818",
    image: "/assets/news/news-0067.jpg",
  },
  {
    id: 66,
    outlet: "DATANET",
    date: "2019.02.25",
    title: "GEMISO Builds 'E.moti.on' at Radio Pakistan",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 26th that it has deployed its radio broadcasting solution 'E.moti.on' at Radio Pakistan Multan.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=131415",
    image: "/assets/news/news-0066.jpg",
  },
  {
    id: 65,
    outlet: "The Electronic Times",
    date: "2019.02.25",
    title: "Korean Radio Broadcasting Solution 'E.moti.on' from GEMISO Enters Pakistan",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced it has successfully completed deployment of its radio broadcasting solution 'E.moti.on' at Radio Pakistan Multan.",
    href: "https://www.etnews.com/20190226000397",
    image: "/assets/news/news-0065.jpg",
  },
  {
    id: 64,
    outlet: "IT Chosun",
    date: "2019.02.25",
    title: "GEMISO Deploys 'E.moti.on' at Radio Pakistan",
    summary: "Digital media management platform company GEMISO announced on the 26th that it has successfully deployed its radio broadcasting solution 'E.moti.on' at Radio Pakistan Multan.",
    href: "http://it.chosun.com/site/data/html_dir/2019/02/26/2019022601401.html",
    image: "/assets/news/news-0064.jpg",
  },
  {
    id: 63,
    outlet: "TechWorld",
    date: "2019.02.25",
    title: "GEMISO Deploys 'E.moti.on' Radio Solution at Pakistan's State Radio Broadcaster",
    summary: "GEMISO announced it has successfully completed deployment of its radio broadcasting solution 'E.moti.on' at Radio Pakistan Multan.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=82600",
    image: "/assets/news/news-0063.jpg",
  },
  {
    id: 62,
    outlet: "Broadcasting & Technology",
    date: "2018.11.29",
    title: "'E.moti.on' Wins Prime Minister's Award at 2018 Radio & Broadcasting Technology Awards",
    summary: "'E.moti.on', the radio production and playout solution developed by EBS, won the Prime Minister's Award at the Radio & Broadcasting Technology Awards.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_d67cc1eab4314cc9afe15e28839659a9.pdf",
    image: "/assets/news/news-0062.jpg",
  },
  {
    id: 61,
    outlet: "Video Arts",
    date: "2018.11.29",
    title: "EBS-GEMISO Radio Broadcasting Solution 'E.moti.on' Officially Recognized for Its Technology",
    summary: "'E.moti.on', the radio broadcasting solution developed by the Korea Educational Broadcasting System (EBS, CEO Jang Hae-rang) and supplied by GEMISO (CEO Kang Jin-wook), won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_5781d9a763ab442bac92692913c18b27.pdf",
    image: "/assets/news/news-0061.jpg",
  },
  {
    id: 60,
    outlet: "Video Plus",
    date: "2018.11.22",
    title: "E.moti.on Wins Prime Minister's Award at Radio & Broadcasting Technology Awards",
    summary: "E.moti.on, the radio broadcasting solution developed by EBS and supplied by GEMISO, won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105361%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0060.jpg",
  },
  {
    id: 59,
    outlet: "Information & Communication Newspaper",
    date: "2018.11.20",
    title: "GEMISO's Radio Broadcasting Solution Wins Prime Minister's Award",
    summary: "'E.moti.on', the radio broadcasting solution developed by the Korea Educational Broadcasting System (EBS) and supplied by GEMISO (CEO Kang Jin-wook), won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74251",
    image: "/assets/news/news-0059.jpg",
  },
  {
    id: 58,
    outlet: "The Electronic Times",
    date: "2018.11.20",
    title: "Radio Broadcasting Solution 'E.moti.on' Wins Prime Minister's Award at Radio & Broadcasting Technology Awards",
    summary: "'E.moti.on', the radio broadcasting solution developed by the Korea Educational Broadcasting System (EBS, CEO Jang Hae-rang) and supplied by GEMISO (CEO Kang Jin-wook), won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "https://www.etnews.com/20181120000416",
    image: "/assets/news/news-0058.jpg",
  },
  {
    id: 57,
    outlet: "DATANET",
    date: "2018.11.19",
    title: "EBS and GEMISO's 'E.moti.on' Wins Prime Minister's Award at Radio & Broadcasting Technology Awards",
    summary: "'E.moti.on', the radio broadcasting solution developed by the Korea Educational Broadcasting System (EBS, CEO Jang Hae-rang) and supplied by GEMISO (CEO Kang Jin-wook), won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=128535",
    image: "/assets/news/news-0057.jpg",
  },
  {
    id: 56,
    outlet: "IT Chosun",
    date: "2018.11.19",
    title: "GEMISO's 'E.moti.on' Wins Prime Minister's Award at Radio & Broadcasting Technology Awards",
    summary: "GEMISO announced on the 20th that its radio broadcasting solution 'E.moti.on' won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "http://it.chosun.com/site/data/html_dir/2018/11/20/2018112001924.html",
    image: "/assets/news/news-0056.jpg",
  },
  {
    id: 55,
    outlet: "IT Biz",
    date: "2018.11.19",
    title: "EBS-GEMISO's 'E.moti.on' Wins Prime Minister's Award at Radio & Broadcasting Technology Awards",
    summary: "'E.moti.on', the radio broadcasting solution developed by the Korea Educational Broadcasting System (CEO Jang Hae-rang; EBS) and supplied by GEMISO (CEO Kang Jin-wook), won the Prime Minister's Award at the 2018 Radio & Broadcasting Technology Awards.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=25879",
    image: "/assets/news/news-0055.jpg",
  },
  {
    id: 54,
    outlet: "Broadcasting & Technology",
    date: "2018.11.04",
    title: "GEMISO Builds MAM System for Digital Conversion and Archiving of Gyeonggi Provincial Council's Video and Photo Assets",
    summary: "GEMISO, a company specializing in digital media management platforms, has successfully completed a video and photo archive system for the Gyeonggi Provincial Council (www.ggc.go.kr).",
    href: "http://tech.kobeta.com/%E3%88%9C%EC%A0%9C%EB%A8%B8%EB%82%98%EC%9D%B4%EC%86%8C%ED%94%84%ED%8A%B8-%EA%B2%BD%EA%B8%B0%EB%8F%84%EC%9D%98%ED%9A%8C-%EC%98%81%EC%83%81%E2%88%99%EC%82%AC%EC%A7%84-%EB%94%94%EC%A7%80%ED%84%B8/",
    image: "/assets/news/news-0054.jpg",
  },
  {
    id: 53,
    outlet: "Video Arts",
    date: "2018.10.30",
    title: "Proxima: A Solution for Small and Mid-Sized Media Archive Systems",
    summary: "A media archive system stores media such as photos, music, and video for the long term and helps users quickly find and reuse the archived media.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_501b02d3fcd84c8fb0bf57ceb71ebf1c.pdf",
    image: "/assets/news/news-0053.png",
  },
  {
    id: 52,
    outlet: "Information & Communication Newspaper",
    date: "2018.10.28",
    title: "GEMISO CEO Kang Jin-wook: \"We Will Become the MAM Leader Customers Recognize\"",
    summary: "GEMISO is a company making its mark in the archive market with homegrown technology. CEO Kang Jin-wook notes that demand for archiving large multimedia assets such as photos and video is on the rise.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74116",
    image: "/assets/news/news-0052.png",
  },
  {
    id: 51,
    outlet: "Video Plus",
    date: "2018.10.17",
    title: "GEMISO Deploys Video and Photo Archive System for Gyeonggi Provincial Council",
    summary: "GEMISO announced it has successfully deployed a video and photo archive system for the Gyeonggi Provincial Council.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105265%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0051.jpg",
  },
  {
    id: 50,
    outlet: "The Electronic Times",
    date: "2018.10.15",
    title: "GEMISO Completes Archive System for Gyeonggi Provincial Council",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced it has successfully completed a video and photo archive system for the Gyeonggi Provincial Council.",
    href: "https://www.etnews.com/20181015000419",
    image: "/assets/news/news-0050.jpg",
  },
  {
    id: 49,
    outlet: "Information & Communication Newspaper",
    date: "2018.10.15",
    title: "GEMISO Wraps Up Archive System for Gyeonggi Provincial Council",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 15th that it has successfully completed a video and photo archive system for the Gyeonggi Provincial Council (www.ggc.go.kr).",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=74038",
    image: "/assets/news/news-0049.jpg",
  },
  {
    id: 48,
    outlet: "IT Daily",
    date: "2018.10.14",
    title: "GEMISO Successfully Finishes Gyeonggi Provincial Council Archive System",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 15th that it has successfully completed the video and photo archive system project for the Gyeonggi Provincial Council.",
    href: "http://www.itdaily.kr/news/articleView.html?idxno=91314",
    image: "/assets/news/news-0048.jpg",
  },
  {
    id: 47,
    outlet: "IT Chosun",
    date: "2018.10.14",
    title: "GEMISO Builds Archive System for Gyeonggi Provincial Council",
    summary: "Digital media management platform company GEMISO announced on the 15th that it has deployed a video and photo archive system for the Gyeonggi Provincial Council. The council has digitized all of its older video and photo materials and migrated them into a single system, enabling integrated management and operation of roughly 650,000 video and photo assets.",
    href: "http://it.chosun.com/site/data/html_dir/2018/10/15/2018101502182.html",
    image: "/assets/news/news-0047.jpg",
  },
  {
    id: 46,
    outlet: "DATANET",
    date: "2018.10.14",
    title: "GEMISO Completes Archive System Deployment for Gyeonggi Provincial Council",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 15th that it has successfully completed a video and photo archive system for the Gyeonggi Provincial Council.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=127322",
    image: "/assets/news/news-0046.jpg",
  },
  {
    id: 45,
    outlet: "ZDNet",
    date: "2018.10.14",
    title: "GEMISO Finishes Archive System for Gyeonggi Provincial Council",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced on the 15th that it has successfully completed a video and photo archive system for the Gyeonggi Provincial Council.",
    href: "https://zdnet.co.kr/view/?no=20181015215436",
    image: "/assets/news/news-0045.jpg",
  },
  {
    id: 44,
    outlet: "Monthly PA",
    date: "2018.09.29",
    title: "Ariel-Based CMS Contract Signed with Huimai Group, China's Largest Video Shopping Company",
    summary: "GEMISO, a company specializing in digital media management platforms, announced it will build a content management system for Beijing Huimai Online Network Science & Technology Co., Ltd., China's largest video shopping (home shopping) service platform company.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_efbd60f09e2e4a11968da5f2efbf5cd7.pdf",
    image: "/assets/news/news-0044.png",
  },
  {
    id: 43,
    outlet: "Video Plus",
    date: "2018.09.29",
    title: "GEMISO Provides Broadcast Solutions to Developing Countries",
    summary: "GEMISO announced it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_7ea712029bec4bdc89b9573c52f7c665.pdf",
    image: "/assets/news/news-0043.png",
  },
  {
    id: 42,
    outlet: "Video Arts",
    date: "2018.09.29",
    title: "GEMISO Supports Developing Countries with Broadcast Solutions",
    summary: "Digital media management platform company GEMISO announced it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance program.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_783e8ca5c04c4f5fb9e82a5767af7042.pdf",
    image: "/assets/news/news-0042.png",
  },
  {
    id: 41,
    outlet: "Broadcasting & Technology",
    date: "2018.09.29",
    title: "GEMISO Supplies Broadcast Solutions to Developing Countries Through RAPA ODA Program",
    summary: "GEMISO will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance program.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_0685c92fe92e4aed89d01f69e6e950cf.pdf",
    image: "/assets/news/news-0041.png",
  },
  {
    id: 40,
    outlet: "TechWorld",
    date: "2018.09.09",
    title: "GEMISO Delivers Broadcast Solutions to Developing Countries",
    summary: "GEMISO, a company specializing in digital media management platforms, announced it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=80992",
    image: "/assets/news/news-0040.png",
  },
  {
    id: 39,
    outlet: "The Electronic Times",
    date: "2018.09.09",
    title: "GEMISO to Deploy Broadcast Solutions in Ethiopia and Pakistan",
    summary: "GEMISO (CEO Kang Jin-wook) announced it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "https://www.etnews.com/20180910000059",
    image: "/assets/news/news-0039.png",
  },
  {
    id: 38,
    outlet: "ZDNet",
    date: "2018.09.08",
    title: "GEMISO to 'Provide Broadcast Solutions to Developing Countries'",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced on the 9th that it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "https://news.naver.com/main/read.naver?mode=LSD&amp;mid=sec&amp;oid=092&amp;aid=0002145602&amp;sid1=001",
    image: "/assets/news/news-0038.png",
  },
  {
    id: 37,
    outlet: "Video Plus",
    date: "2018.09.06",
    title: "GEMISO Brings Broadcast Solutions to Developing Countries",
    summary: "GEMISO announced it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's (RAPA) Official Development Assistance (ODA) program.",
    href: "http://videoplus.co.kr/board_view.php?data=idx%3D105168%26pagecnt%3D%26letter_no%3D%26offset%3D%26search%3D%26searchstring%3D%26present_num%3D&amp;boardIndex=1",
    image: "/assets/news/news-0037.png",
  },
  {
    id: 36,
    outlet: "Digital Daily",
    date: "2018.09.06",
    title: "GEMISO Supplies Broadcast Solutions to Developing Countries",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "https://www.ddaily.co.kr/news/article/?no=172551",
    image: "/assets/news/news-0036.png",
  },
  {
    id: 35,
    outlet: "DATANET",
    date: "2018.09.06",
    title: "GEMISO Supports Ethiopia and Pakistan with Broadcast Solutions",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=126272",
    image: "/assets/news/news-0035.png",
  },
  {
    id: 34,
    outlet: "IT Chosun",
    date: "2018.09.06",
    title: "GEMISO Provides Broadcast Solutions to Developing Countries Including Ethiopia and Pakistan",
    summary: "Digital media management platform company GEMISO announced on the 7th that it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "http://it.chosun.com/site/data/html_dir/2018/09/07/2018090702353.html",
    image: "/assets/news/news-0034.png",
  },
  {
    id: 33,
    outlet: "Financial Newspaper",
    date: "2018.09.06",
    title: "GEMISO Delivers Broadcast Solutions to Ethiopia and Pakistan",
    summary: "GEMISO, a company specializing in digital media management platforms, announced on the 7th that it will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "http://www.efnews.co.kr/news/articleView.html?idxno=76695",
    image: "/assets/news/news-0033.png",
  },
  {
    id: 32,
    outlet: "KINEWS",
    date: "2018.09.06",
    title: "GEMISO Aids Developing Countries with Broadcast Solutions",
    summary: "Digital media management platform company GEMISO will supply its broadcast solutions to Ethiopia and Pakistan through the Korea Radio Promotion Association's Official Development Assistance (ODA) program.",
    href: "",
    image: "/assets/news/news-0032.png",
  },
  {
    id: 31,
    outlet: "Video Arts",
    date: "2018.08.30",
    title: "GEMISO and China's Huimai Group Sign CMS Contract",
    summary: "GEMISO (CEO Kang Jin-wook, www.gemiso.com), a company specializing in digital media management platforms, announced it will build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd., China's largest video shopping (home shopping) service platform company.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_31b480e66de2433eb28fec206564ac2f.pdf",
    image: "/assets/news/news-0031.png",
  },
  {
    id: 30,
    outlet: "Broadcasting & Technology",
    date: "2018.08.30",
    title: "GEMISO Signs CMS Contract with China's Huimai Group",
    summary: "GEMISO, a company specializing in digital media management platforms, will build a content management system for Beijing Huimai Online Network Science & Technology Co., Ltd., China's largest video shopping service platform company.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_519d94d20218480c81c65b475b95d52a.pdf",
    image: "/assets/news/news-0030.jpg",
  },
  {
    id: 29,
    outlet: "Monthly PA",
    date: "2018.08.30",
    title: "'E.moti.on': A Comprehensive Broadcast Solution Focused on Field-Ready Features",
    summary: "Developed by the Korea Educational Broadcasting System and supplied by GEMISO, E.moti.on is a file-based integrated radio system built on EBS's long broadcasting know-how and in-house technology.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_5e2bab6e29f24023a539121ce28b1c95.pdf",
    image: "/assets/news/news-0029.jpg",
  },
  {
    id: 28,
    outlet: "Video Plus",
    date: "2018.08.30",
    title: "'Distributed Processing': The Core Technology of UHD MAM",
    summary: "GEMISO was ahead of the curve in bringing distributed transcoding technology, which handles UHD video faster and more efficiently, into its MAM system.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_9874a46e5647436697f3045fba9ca1e9.pdf",
    image: "/assets/news/news-0028.png",
  },
  {
    id: 27,
    outlet: "Video Plus",
    date: "2018.08.30",
    title: "GEMISO Signs Contract to Build CMS for China's Huimai Group",
    summary: "GEMISO announced it has signed a contract to build a content management system for Beijing Huimai Online Network Science & Technology Co., Ltd., a Chinese video shopping service platform company.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_4dc03e0e28264557a8c9694c66f8d315.pdf",
    image: "/assets/news/news-0027.png",
  },
  {
    id: 26,
    outlet: "The Electronic Times",
    date: "2018.08.06",
    title: "Korean CMS 'Ariel' Powers China's Largest Home Shopping Platform",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced it will build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd. (Huimai Group, CEO Du Ruiyong), China's largest video shopping (home shopping) service platform company.",
    href: "https://www.etnews.com/20180807000098",
    image: "/assets/news/news-0026.png",
  },
  {
    id: 25,
    outlet: "KINEWS",
    date: "2018.08.06",
    title: "GEMISO Signs CMS Deal with China's Huimai Group",
    summary: "Digital media management platform company GEMISO (CEO Kang Jin-wook) announced on the 7th that it will build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd. (Huimai Group), a Chinese video shopping (home shopping) service platform company.",
    href: "",
    image: "/assets/news/news-0025.png",
  },
  {
    id: 24,
    outlet: "IT Biz",
    date: "2018.08.06",
    title: "GEMISO to Build Content Management System for China's Huimai Group",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it will build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd. (Huimai Group, CEO Du Ruiyong), a Chinese video shopping service platform company.",
    href: "http://www.it-b.co.kr/news/articleView.html?idxno=23304",
    image: "/assets/news/news-0024.png",
  },
  {
    id: 23,
    outlet: "IT Chosun",
    date: "2018.08.06",
    title: "GEMISO Signs CMS Contract with China's Huimai Group",
    summary: "Digital media management platform company GEMISO announced on the 7th that it has signed a contract to build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd. (Huimai Group), China's largest video shopping (home shopping) service platform company.",
    href: "http://it.chosun.com/site/data/html_dir/2018/08/07/2018080701137.html",
    image: "/assets/news/news-0023.png",
  },
  {
    id: 22,
    outlet: "Digital Daily",
    date: "2018.08.06",
    title: "GEMISO Inks CMS Contract with China's Huimai Group",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it has signed a content management system (CMS) contract with Huimai Group, China's largest video shopping (home shopping) service platform company.",
    href: "https://www.ddaily.co.kr/news/article/?no=171432",
    image: "/assets/news/news-0022.png",
  },
  {
    id: 21,
    outlet: "DATANET",
    date: "2018.08.06",
    title: "GEMISO Lands CMS Deal with China's Huimai Group",
    summary: "GEMISO (CEO Kang Jin-wook) announced on the 7th that it will build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd. (Huimai Group, CEO Du Ruiyong), China's largest video shopping (home shopping) service platform company.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=125315",
    image: "/assets/news/news-0021.png",
  },
  {
    id: 20,
    outlet: "Interface News",
    date: "2018.08.06",
    title: "GEMISO Kicks Off CMS Build for China's Huimai Group",
    summary: "Digital media management platform company GEMISO announced it will build a content management system (CMS) for Beijing Huimai Online Network Science & Technology Co., Ltd. (Huimai Group), China's largest video shopping (home shopping) service platform company.",
    href: "",
    image: "/assets/news/news-0020.png",
  },
  {
    id: 19,
    outlet: "Information & Communication Newspaper",
    date: "2018.08.06",
    title: "GEMISO to Supply Content Management System in China",
    summary: "GEMISO, a company specializing in digital media management platforms, announced it will build a content management system (CMS) for Huimai Online Network Science & Technology Co., Ltd. (Huimai Group), China's largest home shopping service platform company.",
    href: "http://www.koit.co.kr/news/articleView.html?idxno=73682",
    image: "/assets/news/news-0019.png",
  },
  {
    id: 18,
    outlet: "Video Arts",
    date: "2018.08.01",
    title: "GEMISO and EBS Sign Radio Solution Supply Contract",
    summary: "GEMISO (CEO Kang Jin-wook, www.gemiso.co.kr), a company specializing in digital media management platforms, announced it has signed an exclusive supply contract with the Korea Educational Broadcasting System (EBS, CEO Jang Hae-rang, www.ebs.co.kr) for the radio broadcasting solution 'E.moti.on'.",
    href: "https://www.videoarts.co.kr/customer/news_view.php?bd_id=2352&amp;page=1&amp;s_start=&amp;s_end=&amp;s_cate=01&amp;s_value=&amp;end_no=10",
    image: "/assets/news/news-0018.jpg",
  },
  {
    id: 17,
    outlet: "Broadcasting & Technology",
    date: "2018.07.31",
    title: "GEMISO and EBS Sign Supply Contract for Radio Solution E.moti.on",
    summary: "GEMISO, a company specializing in digital media management platforms, has signed an exclusive supply contract with EBS for the radio broadcasting solution 'E.moti.on'.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_12b528dfe4534d3889ce1042552436a7.pdf",
    image: "/assets/news/news-0017.jpg",
  },
  {
    id: 16,
    outlet: "Video Plus",
    date: "2018.07.31",
    title: "GEMISO-EBS Radio Solution Supply Contract Signed",
    summary: "On July 19, GEMISO signed an exclusive supply contract with the Korea Educational Broadcasting System (EBS) for the radio broadcasting solution 'E.moti.on'.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_07197ffd48be46fcb2ce15eef1e2d8e0.pdf",
    image: "/assets/news/news-0016.jpg",
  },
  {
    id: 15,
    outlet: "Interface News",
    date: "2018.07.19",
    title: "GEMISO and EBS Conclude Radio Solution Supply Contract",
    summary: "GEMISO, a company specializing in digital media management platforms, announced it has signed an exclusive supply contract with the Korea Educational Broadcasting System (EBS) for the radio broadcasting solution 'E.moti.on'.",
    href: "",
    image: "/assets/news/news-0015.jpg",
  },
  {
    id: 14,
    outlet: "The Electronic Times",
    date: "2018.07.19",
    title: "GEMISO Partners with EBS to Supply 'E.moti.on', an Easy-to-Install-and-Operate Radio Broadcasting Solution",
    summary: "Digital media management company GEMISO (CEO Kang Jin-wook) announced on the 19th that it has signed an exclusive supply contract with the Korea Educational Broadcasting System (EBS, CEO Jang Hae-rang) for the radio broadcasting solution 'E.moti.on'.",
    href: "https://www.etnews.com/20180719000293",
    image: "/assets/news/news-0014.png",
  },
  {
    id: 13,
    outlet: "Yonhap News",
    date: "2018.07.18",
    title: "EBS Moves to Distribute Its In-House Radio Broadcasting Solution",
    summary: "EBS has begun distributing its in-house radio broadcasting solution.",
    href: "https://www.yna.co.kr/view/AKR20180719149400005",
    image: "/assets/news/news-0013.jpg",
  },
  {
    id: 12,
    outlet: "Yonhap News",
    date: "2018.07.18",
    title: "Photo News: EBS Moves to Distribute Its In-House Radio Broadcasting Solution",
    summary: "EBS said it signed a contract with GEMISO on the 19th at its Ilsan headquarters in Goyang, Gyeonggi Province, to pursue a partnership for its in-house radio broadcasting solution 'E.MOTI.ON'.",
    href: "https://www.yna.co.kr/view/PYH20180719215400005",
    image: "/assets/news/news-0012.jpg",
  },
  {
    id: 11,
    outlet: "Newsen",
    date: "2018.07.18",
    title: "EBS Signs Partnership Contract with GEMISO for In-House Radio Broadcasting Solution",
    summary: "EBS has signed a contract with GEMISO to pursue a partnership.",
    href: "https://www.newsen.com/news_view.php?uid=201807191813128010",
    image: "/assets/news/news-0011.jpg",
  },
  {
    id: 10,
    outlet: "DATANET",
    date: "2018.07.18",
    title: "GEMISO and EBS Sign Supply Contract for Radio Solution",
    summary: "GEMISO (CEO Kang Jin-wook), a company specializing in digital media management platforms, announced it has signed an exclusive supply contract with the Korea Educational Broadcasting System (CEO Jang Hae-rang; EBS) for the radio broadcasting solution 'E.moti.on'.",
    href: "http://www.datanet.co.kr/news/articleView.html?idxno=124769",
    image: "/assets/news/news-0010.jpg",
  },
  {
    id: 9,
    outlet: "Broadcasting & Technology",
    date: "2018.05.30",
    title: "GEMISO Unveils Three Next-Generation Broadcast Solutions at KOBA 2018",
    summary: "GEMISO exhibited and demonstrated three new solutions for the next-generation broadcast environment at KOBA 2018.",
    href: "https://ba0baf98-1b92-4a3e-8ed6-db31fc82621c.filesusr.com/ugd/7bafc1_2acc7e9a6877418487c78ebaa564aa7b.pdf",
    image: "/assets/news/news-0009.png",
  },
  {
    id: 8,
    outlet: "IT Chosun",
    date: "2018.05.10",
    title: "[Software of the Week] Unity '2018.1', Upbit 'Cryptocurrency Index', and GEMISO Solutions in the Spotlight",
    summary: "GEMISO's 'Ariel' is a digital asset management solution that introduces project-based media management technology.",
    href: "http://it.chosun.com/site/data/html_dir/2018/05/11/2018051185026.html",
    image: "/assets/news/news-0008.png",
  },
  {
    id: 7,
    outlet: "IT Chosun",
    date: "2018.05.09",
    title: "GEMISO Unveils Solutions for the Next-Generation Broadcast Environment at KOBA 2018",
    summary: "GEMISO announced it will exhibit and demonstrate three new solutions for the next-generation broadcast environment at KOBA 2018.",
    href: "http://it.chosun.com/site/data/html_dir/2018/05/10/2018051085055.html",
    image: "/assets/news/news-0007.png",
  },
  {
    id: 6,
    outlet: "Interface News",
    date: "2018.05.08",
    title: "GEMISO Announces 'UHD MAM, Radio Broadcasting, and AR' Broadcast Solutions",
    summary: "GEMISO will exhibit and demonstrate three new solutions for the next-generation broadcast environment at KOBA 2018.",
    href: "",
    image: "/assets/news/news-0006.png",
  },
  {
    id: 5,
    outlet: "TechWorld",
    date: "2018.05.08",
    title: "GEMISO Announces Next-Generation Broadcast Solutions Including AR and UHD MAM",
    summary: "GEMISO will unveil three solutions for the next-generation broadcast environment at KOBA 2018.",
    href: "http://www.epnc.co.kr/news/articleView.html?idxno=79916",
    image: "/assets/news/news-0005.png",
  },
  {
    id: 4,
    outlet: "IT World",
    date: "2018.05.08",
    title: "GEMISO Announces Three Next-Generation Broadcast Solutions",
    summary: "GEMISO announced it will exhibit and demonstrate three new solutions for the next-generation broadcast environment at KOBA 2018.",
    href: "https://www.itworld.co.kr/news/109238",
    image: "/assets/news/news-0004.png",
  },
  {
    id: 3,
    outlet: "CIO Korea",
    date: "2018.05.08",
    title: "GEMISO Presents Three Next-Generation Broadcast Solutions",
    summary: "GEMISO announced it will exhibit and demonstrate three new solutions for the next-generation broadcast environment at KOBA 2018.",
    href: "https://www.ciokorea.com/news/38184",
    image: "/assets/news/news-0003.png",
  },
  {
    id: 2,
    outlet: "AVING",
    date: "2018.05.07",
    title: "[KOBA 2018 Preview] GEMISO to Announce Three Next-Generation Broadcast Solutions",
    summary: "GEMISO will take part in the Korea International Broadcast, Audio & Lighting Equipment Show (KOBA 2018), showcasing three new solutions for the next-generation broadcast environment.",
    href: "http://kr.aving.net/news/view.php?articleId=1385973&amp;Branch_ID=kr&amp;rssid=naver&amp;mn_name=news",
    image: "/assets/news/news-0002.png",
  },
  {
    id: 1,
    outlet: "",
    date: "2018.04.24",
    title: "CJ O Shopping Adopts GEMISO's AR Solution",
    summary: "GEMISO's AR (augmented reality) 3D graphics solution 'Nemesis' has been applied to live broadcasts through CJ O Shopping's AR studio.",
    href: "",
    image: "/assets/news/news-0001.png",
  },
];

/** id로 기사 한 건을 찾는다. */
export function getArticle(id: string | number): NewsArticle | undefined {
  const n = typeof id === "string" ? Number(id) : id;
  return NEWS_ARTICLES.find((a) => a.id === n);
}

/** 현재 기사를 제외한 관련 소식(최신순)을 count개 반환한다. */
export function relatedArticles(id: number, count = 3): NewsArticle[] {
  return NEWS_ARTICLES.filter((a) => a.id !== id).slice(0, count);
}
